package main

import (
	"fmt"
	"regexp"
	"strings"
	"sync"

	"github.com/samber/lo"
)

const md string = `# Causes of airway compromise

- Angioedema
- Anaphylaxis
- Thermal injury
- Neck haematoma
- Wheeze
- Surgical emphysema
- Reduced consciousness

# Simple airway manoeuvres

- Suction: if visible vomit, blood, secretions or foreign body
  - Turn patient onto side if actively vomiting (not applicable in C-Spine injury)
- Head tilt/chin lift
  - Can be achieved manually or by placing a pillow under the neck
  - Aim for the 'sniffing' position
- Jaw thrust
  - Using both hands, hook the fingers under the angle of the patient's jaw and lift the mandible forwards

# Airway adjuncts

- Oropharyngeal airway (OPA) e.g. Guedel
  - Rigid plastic tube
  - Appropriately measured from the incisors to the angle of the jaw
  - Inserted 'upside down' and rotated 180 degrees to hold the tongue away from the posterior pharynx
- Nasopharyngeal airway (NPA)
  - Flexible rubber tube
  - Pass through one anterior nasal passage to sit inferior to the base of the tongue
  - Useful in patients with a sensitive gag reflex when using OPA
  - Contraindicated in base of skull fracture

# Supraglottic airway

- Laryngeal mask airway (LMA) or i-Gel

- Flexible plastic tube with inflatable cuff
- Sits over the top of the larynx
- Can be used with ventilation machine

# Endotracheal (ET) tube

- Flexible plastic tube with inflatable cuff
- Inserted using a laryngoscope
- Used for prolonged mechanical ventilation
- 'Protected airway' - protects against aspiration

# Surgical airways

- Tracheostomy
- Cricothyroidotomy

# External links

[- Resuscitation Council: ABCDE Approach](https://www.APTT.org.uk/print/pdf/node/123)
[- Life In The Fast Lane: Airway Management](https://litfl.com/airway-management/)
`

var conceptNameList = []string{
	"1st line treatment for streptococcal tonsillitis - penicillin V",
	"ACE inhibitors",
	"ACE-i - dry cough",
	"ACEi for 2nd stage hypertension - monitor U&Es during initiation of treatment",
	"ACEi mechanism of action",
	"ADHD in children - methyphenidate",
	"ADPKD (Autosomal-Dominant (Adult) Polycystic Kidney Disease)",
	"AF - warfarin appropriate to CHA2DS2VASc",
	"AIDS defining illnesses",
	"APTT",
	"ARDS",
	"ASA guidelines",
	"Abdominal Scars",
	"Abdominal Vasculature—Anterior Abdominal Wall",
	"Abdominal Vasculature—The Abdominal Aorta",
	"Abdominal Vasculature—The Abdominal Aorta",
	"Abdominal Vasculature—The Celiac Trunk",
	"Abdominal Vasculature—The Inferior Mesenteric Artery",
	"Abdominal Vasculature—The Superior Mesenteric Artery",
	"Abdominal aortic aneurysms",
	"Abnormal VQ in the upper and lower normal lung",
	"Acarbose",
	"Ace-inhibitor Side Effects",
	"Achalasia",
	"Achalasia",
	"Achalasia",
	"Achilles Tendonitis",
	"Acid-Base Balance",
	"Acne Rosacea",
	"Acne Vulgaris",
	"Acne vulgaris algorithm - after no response to topical treatment, prescribe oral tetracycline",
	"Acromegaly",
	"Acromioclavicular Joint",
	"Acrosome Reaction",
	"Actinic Keratosis",
	"Action of thyroid hormones",
	"Action of vasopressin",
	"Action of vasopressin",
	"Actions of Oxytocin",
	"Actions of Vasopressin",
	"Actions of aldosterone",
	"Actions of growth hormone",
	"Actions of medullary catecholamines",
	"Actions of medullary catecholamines",
	"Active management of the third stage of labour",
	"Acute Epiglottitis",
	"Acute Epiglottitis in Adults",
	"Acute Lymphoblastic Leukaemia in children",
	"Acute Lymphocytic Leukaemia in children",
	"Acute Paracetamol Overdose - mechanism of liver damage",
	"Acute Tonsillitis",
	"Acute Tubular Necrosis",
	"Acute Tubular Necrosis",
	"Acute asthma in children",
	"Acute asthma in children",
	"Acute bradycardia",
	"Acute cholecystitis",
	"Acute fatty liver of pregnancy",
	"Acute fatty liver of pregnancy",
	"Acute intermittent porphyria",
	"Acute intermittent porphyria",
	"Acute interstitial nephritis",
	"Acute kidney injury",
	"Acute limb ischaemia",
	"Acute mesenteric ischaemia",
	"Acute monoarthritis (Red hot joint)",
	"Acute myocarditis",
	"Acute narrow complex tachycardias",
	"Acute narrow complex tachycardias",
	"Acute otitis media (paediatrics)",
	"Acute otitis media (paediatrics)",
	"Acute pancreatitis",
	"Acute pancreatitis",
	"Acute pancreatitis",
	"Acute pancreatitis",
	"Acute phase reactants",
	"Acute porphyrias",
	"Acute pulmonary oedema - furosemide for symptomatic relief",
	"Acute respiratory distress syndrome",
	"Acute respiratory distress syndrome",
	"Acute urinary retention",
	"Acute urinary retention",
	"Acute urinary retention",
	"Acyanotic heart disease",
	"Adductor Canal",
	"Adenoidectomy",
	"Adenylyl cyclase and cAMP signalling pathways",
	"Adipose Tissue",
	"Adrenal Endocrinology",
	"Adrenal Glands",
	"Adrenal insufficiency and Addison's Disease",
	"Adrenal insufficiency and Addison's Disease",
	"Adrenergic stimulation of uterine smooth muscle",
	"Adult respiratory distress pathophysiology",
	"Adult-onset Still's disease",
	"Advanced Life Support",
	"Age related macular degeneration",
	"Airway Management",
	"Airway Management",
	"Albumin Binding of Drugs",
	"Alcohol units",
	"Alcohol withdrawal",
	"Alcohol withdrawal",
	"Aldosterone receptor antagonism vs reduced aldosterone production",
	"Alendronic acid",
	"Allergic Rhinitis",
	"Allosteric inhibition",
	"Alopecia",
	"Alpha blockers and postural hypotension: tamsulosin given for BPH",
	"Alpha fetoprotein (AFP)",
	"Alpha-1 Antitrypsin Deficiency",
	"Alpha-2-adrenergic receptors and adenylyl cyclase activity",
	"Alpha-gamma motor neuron co-activation",
	"Alveolar ventilation calculations",
	"Alzheimer's",
	"Alzheimer's disease",
	"Alzheimer's disease",
	"Amblyopia",
	"Amenorrhoea",
	"Amino acid absorption",
	"Amino acid and small peptide absorption in the small intestine",
	"Amino acid metabolism (transamination and deamination)",
	"Amino acids (chemistry and structure)",
	"Aminophylline infusions after back-to-back salbutamol - caution hypokalaemia",
	"Amiodarone - CXR before initiating treatment",
	"Amiodarone induced Thyrotoxicosis",
	"Amlodipine - peripheral oedema",
	"Amniotic fluid embolism",
	"Amphetamine mechanism of action",
	"Amyloidosis",
	"Amyloidosis kidney microscopic",
	"Anaemia in infants and children",
	"Anaemia of chronic disease",
	"Anal Triangle",
	"Anal canal",
	"Anal fistula",
	"Anaphylaxis (Paediatrics)",
	"Anaphylaxis treatment",
	"Anatomical Snuffbox",
	"Anatomy of auditory nerve fibres",
	"Anatomy of auditory pathways",
	"Anatomy of auditory pathways",
	"Anatomy of the arousal system",
	"Anatomy of the corticospinal tract",
	"Anatomy of the corticospinal tract",
	"Anatomy of the deep cerebellar nuclei",
	"Anatomy of the dorsal columns",
	"Anatomy of the pupillary light reflex",
	"Anatomy of the spinal cord grey matter",
	"Anatomy of the spinocerebellar tract",
	"Anatomy of the spinothalamic tracts",
	"Anatomy of visual pathways",
	"Anencephaly",
	"Aneurysms in vascular surgery",
	"Aneurysms in vasular surgery",
	"Angiodysplasia",
	"Angiotensin receptor blockers",
	"Ankle joint",
	"Ankylosing spondylitis",
	"Ann Arbor staging system",
	"Anorectal abscess",
	"Anorexia nervosa",
	"Antacids",
	"Antepartum haemorrhage",
	"Anterior Forearm muscles",
	"Anterior Spinal Artery infarct",
	"Anterior cranial fossa",
	"Anterior mediastinum",
	"Anterior shoulder dislocation",
	"Anterior triangle",
	"Anterolateral Abdominal Wall Muscles",
	"Anti-diabetic drugs mechanisms of action",
	"Anti-emetics",
	"Anti-emetics",
	"Anti-glomerular basement membrane disease",
	"Anti-platelet effects of NSAIDs",
	"Anti-psychotic side effects",
	"Antibiotic choice",
	"Antibiotics",
	"Antibodies in gastrointestinal disease",
	"Antibodies in renal disease",
	"Antibodies in rheumatological disease",
	"Antibody concentration as a marker for infection status",
	"Antibody half-life determination",
	"Antibody structure",
	"Antidepressant mechanism of action",
	"Antidiuretic hormone effect on the collecting duct",
	"Antigen Presentation",
	"Antimuscarinic agents",
	"Antiphospholipid syndrome",
	"Antipsychotics cuasing worsening parkinsonism in LBD",
	"Anxiety, Obsessions and Stress Reactions",
	"Aorta with lipid streaks",
	"Aortic arch",
	"Aortic dissection",
	"Aortic dissection",
	"Aortic regurgitation",
	"Aortic stenosis",
	"Aplastic anaemia",
	"Apparent volume of distribution",
	"Appendicitis",
	"Appendix",
	"Applied Neuroanatomy",
	"Applied Respiratory Anatomy",
	"Approach to Epigastric pain",
	"Approach to central abdominal pain",
	"Approach to central abdominal pain",
	"Approach to haematuria",
	"Approach to knee radiographs",
	"Approximating body surface area in burns",
	"Aqueous component of pancreatic juice",
	"Arm: Nerves",
	"Arm: Vessels",
	"Aromatase inhibitors",
	"Arterial Supply of the abdomen",
	"Arterial Supply of the arm",
	"Arterial and Venous ulcers",
	"Arterial blood gas interpretation",
	"Arterial supply of the lower limb",
	"Arterial, venous and nervous supply of the scalp",
	"Arteries of the pelvis",
	"Asbestosis",
	"Asbestosis",
	"Ascending cholangitis",
	"Ascending cholangitis",
	"Ascending cholangitis",
	"Ascites",
	"Aspects of Sulphonamide use",
	"Aspects of cephalosporin use",
	"Aspiration Pneumonia",
	"Assessment and management of C-Spine injury",
	"Assessment and management of C-Spine injury",
	"Assessment of a patient with hyperlipidaemia",
	"Assessment of pain in a surgical patient",
	"Asthma",
	"Asthma",
	"Asthma",
	"Asthma",
	"Asthma",
	"Asthma",
	"Asthma - microscopic",
	"Asthma in children",
	"Asthma in children",
	"Asthma pathophysiology",
	"Asymptomatic bacteriuria in pregnancy",
	"At risk groups for pneumococcal vaccine",
	"Atherosclerotic pathway",
	"Atopic dermatitis",
	"Atorvastatin - recommend LFTs at 3 months",
	"Atrial Fibrillation",
	"Atrial Flutter",
	"Atrial Flutter",
	"Atrial fibrillation",
	"Atrial septal defect",
	"Atrophic vaginitis",
	"Atropine poisoning",
	"Attention deficit hyperactivity disorder (ADHD)",
	"Atypical anti-psychotics mechanism of action",
	"Atypical antipsychotic",
	"Atypical antipsychotics",
	"Atypical facial pain (acute rhinosinusitis)",
	"Autistic spectrum disorders",
	"Autoimmune destruction in Addisons disease",
	"Autoimmune destruction in Type 1 Diabetes Mellitus",
	"Autoimmune disease",
	"Autoimmune disease in blood cells",
	"Autoimmune encephalitis",
	"Autoimmune hepatitis",
	"Autoimmune hyperthyroidism",
	"Autoimmune hypothyroidism",
	"Autoimmune joint disease",
	"Autoimmune mechanisms",
	"Autonomic Nervous System",
	"Autonomic Neuropathy",
	"Autonomic control of gastrointestinal motility",
	"Autosomal Dominant Conditions",
	"Autosomal Recessive Conditions",
	"Avascular necrosis",
	"Avascular necrosis",
	"Axillary nerve injury",
	"Axillary nerve injury",
	"B cell receptor properties",
	"B cells",
	"B2 agonists",
	"Baby blues",
	"Back pain",
	"Back: Muscles—Deep",
	"Back: Muscles—Superficial",
	"Back: Vertebral Column - Cervical",
	"Back: Vertebral Column—Lumbar & Sacral",
	"Back: Vertebral Column—Overview",
	"Back: Vertebral Column—Thoracic",
	"Back: Vertebral Column—Vertebral",
	"Bacterial Vaginosis",
	"Bacterial Vaginosis",
	"Bacterial keratitis",
	"Bacterial tracheitis",
	"Baker's cyst",
	"Balanoposthitis",
	"Baroreceptor reflex",
	"Barret's oesophagus",
	"Barrett's oesophagus",
	"Barrett's oesophagus",
	"Bartholin’s gland",
	"Basal Cell Carcinoma (BCC)",
	"Basal cell carcinoma of the eyelid",
	"Basal ganglia circuits",
	"Basal ganglia haemorrhage macroscopic",
	"Basal ganglia haemorrhage macroscopic",
	"Basal ganglia haemorrhage macroscopic",
	"Basal skull fracture",
	"Basal skull fracture",
	"Basophils properties",
	"Before giving ulipristal acetate for EC - no LFTs needed (only for fibroids)",
	"Before initiating antipsychotic therapy - baseline prolactin",
	"Before starting COCP - do BP",
	"Before starting clozapine - FBC",
	"Before starting donepezil - ECG",
	"Behcet's disease",
	"Bell's Palsy",
	"Bell's Palsy",
	"Bella donna poisoning",
	"Benign and malignant tumours",
	"Benign breast disease",
	"Benign paroxysmal positional vertigo (BPPV)",
	"Benign tumours of the eyelid",
	"Bennett Fracture",
	"Bennett Fracture",
	"Benzodiazepine Half life",
	"Best interest decisions in patients who lack capacity",
	"Beta blocker for stable angina - exercise tolerance as a measure of treatment benefit",
	"Beta blocker use in heart failure",
	"Beta oxidation of fatty acids",
	"Bicarbonate reabsorption",
	"Bicep Tendon Tear",
	"Bilateral hilar lymphadenopathy",
	"Bile structure, function and metabolism",
	"Biliary atresia",
	"Biliary tree structure",
	"Bipartite Patella",
	"Bipartite Patella",
	"Bipolar Affective Disorder",
	"Bladder cancer",
	"Blastulation",
	"Bleeding disorders associated with liver disease and malabsorption",
	"Blepharitis",
	"Blood film findings",
	"Blood flow through the heart",
	"Blood group compatibility",
	"Blood tests before starting statins",
	"Blood-Testis Barrier",
	"Boerhaave syndrome",
	"Bolam Test",
	"Bolitho Ruling",
	"Bone Matrix Mineralisation",
	"Bone Pathology",
	"Bone composition",
	"Bone extracellular matrix",
	"Bone malignancies",
	"Bone remodelling",
	"Bones of the Foot",
	"Bones of the Hand",
	"Bones of the cranium",
	"Bones of the face",
	"Booking appointment (obstetrics)",
	"Booking appointment (obstretrics)",
	"Borders of the femoral triangle",
	"Borders of the heart",
	"Borreliosis",
	"Botulin toxin mechanism",
	"Box and whisker plots",
	"Boxer's Fracture",
	"Boxer's Fracture",
	"Brachial Plexus",
	"Brachial Plexus—Axillary Nerve",
	"Brachial Plexus—Median Nerve",
	"Brachial Plexus—Median Nerve",
	"Brachial Plexus—Musculocutaneous Nerve",
	"Brachial Plexus—Musculocutaneous Nerve",
	"Brachial Plexus—Radial Nerve",
	"Brachial Plexus—Ulnar Nerve",
	"Brachial plexus injuries",
	"Brachial plexus injuries",
	"Brachial plexus injuries",
	"Bradycardia",
	"Brain tumours in children",
	"Branchial cyst",
	"Branchial cyst",
	"Branchial cyst",
	"Breakdown of fatty acids to form acetyl CoA",
	"Breast Cancer",
	"Breastfeeding",
	"Breastfeeding",
	"Breastfeeding",
	"Breath holding seizures and reflex anoxic seizures",
	"Breech presentation",
	"Broad Complex Tachycardia",
	"Broad Complex Tachycardias",
	"Bronchial tree",
	"Bronchiectasis",
	"Bronchiolitis",
	"Bronchiolitis Mx - no other Rx apart from oxygen as no benefit",
	"Bronchiolitis obliterans",
	"Brown Sequard Syndrome",
	"Brown-Sequard Syndrome",
	"Brown-Séquard Syndrome",
	"Brown-sequard Syndrome",
	"Brucellosis",
	"Brugada syndrome",
	"Bruising as side effect of Warfarin",
	"Buerger's disease (thromboangiitis obliterans)",
	"Bulbar palsy",
	"Bulbo-urethral glands",
	"Bulimia",
	"Burns",
	"Burns",
	"CCB for 2nd stage hypertension - no routine monitoring required (apart from BP)",
	"COCP - rifampicin interaction",
	"COCP – Missing pill rules",
	"COPD pathophysiology",
	"CSF rhinorrhoea",
	"CYP3A4 gene transcription",
	"Caecum",
	"Caesarian section",
	"Calcaneal fractures",
	"Calcium absorption",
	"Calcium channel antagonism",
	"Calcium channel blocker side effects",
	"Calcium channel blockers in epilepsy",
	"Calcium channel blockers in epilepsy",
	"Calcium levels",
	"Calculate amount (g) of 10% glucose given to DKA patient after nth hour given infusion rate of 125mL/hour",
	"Calculate amount of K (mmol) given after nth hour of maintenance fluids",
	"Calculate the maximum number of tramadol tablets that can be given on discharge for a duration of 10 days given dosage",
	"Calculate volume of drug needed given concentration + weight based dosing: amoxicillin (syrup)",
	"Calculation of dose when changing formulation with same bioquivalence- Carbamazepine (tablet to suppositories)",
	"Calculation of dose when changing formulation with same bioquivalence- Carbamazepine (tablet to suppositories)",
	"Calculation of dose when changing formulation with same bioquivalence- Carbamazepine (tablet to suppositories)",
	"Calculation of drug volume to be administered based on known dose and concentration",
	"Calculation of infusion rate",
	"Calculation of infusion rate",
	"Calculation of infusion rate",
	"Calculation of infusion rate",
	"Calculation of infusion rate",
	"Calculation of strength of infusion drug based on given dose and volume - Phenytoin",
	"Calculation of total body water",
	"Calculation of volume needed given concentration + weight based dosing- Clarithomycin",
	"Calculation of volume of 0.9% NS (1unit/mL) with insulin + weight based dosing (0.1u/kg/hr) given for treatment of DKA",
	"Calculations",
	"Calculations",
	"Calculations of Alcohol Units 1",
	"Calculations of Alcohol Units 2",
	"Cancer Epidemiology",
	"Cancer Pathology",
	"Candida Albicans",
	"Capacitation",
	"Caput succedaneum",
	"Carbimazole",
	"Carbimazole",
	"Carbohydrate absorption in the small intestine",
	"Carbohydrate chemistry",
	"Carcinoid tumours",
	"Carcinoid tumours",
	"Cardiac Action Potential Generation and Conduction",
	"Cardiac Tamponade",
	"Cardiac Volumes and Arterial Pressure",
	"Cardiac amyloid",
	"Cardiac catheterisation",
	"Cardiac effects of Angiotensin II",
	"Cardiac folding",
	"Cardiac myxoma",
	"Cardiac pacing",
	"Cardiomyopathies",
	"Carotid cavernous fistula",
	"Carpal tunnel syndrome",
	"Carpal tunnel syndrome",
	"Cartilage and Endochondral Ossification",
	"Cataract surgery",
	"Cataracts",
	"Cauda Equina Syndrome",
	"Causes of death in cancer",
	"Causes of dysphagia",
	"Causes of dysphagia",
	"Causes of gynaecomastia",
	"Causes of high platelets",
	"Causes of low platelets",
	"Causes of massive splenomegaly",
	"Causes of primary amenorrhoea",
	"Causes of respiratory acidosis",
	"Causes of short stature",
	"Causes of sterile pyuria",
	"Causes of ventilation perfusion mismatch",
	"Cautions in drugs that cause bronchospasm",
	"Cell organelles",
	"Cellular And Molecular Biology Of Bone",
	"Cellulitis",
	"Cellulitis",
	"Cellulitis - if pen allergic then 2nd line is clindamycin",
	"Cellulitis and Erysipelas",
	"Cement embolism",
	"Central chemoreceptors",
	"Central retinal vein occlusion (CRVO)",
	"Cerebellar abscess",
	"Cerebellar cell types",
	"Cerebellar climbing fibres",
	"Cerebellar syndrome",
	"Cerebral amyloid angiopathy",
	"Cerebral palsy",
	"Cerebral stroke",
	"Cerebral stroke",
	"Cervical Mucus",
	"Cervical Spondylosis",
	"Cervical cancer",
	"Cervical lymphadenopathy",
	"Cervix",
	"Chambers of the heart",
	"Chancroid",
	"Characteristics of ligand-gated and voltage-gated channels",
	"Characteristics of the parasympathetic nervous system",
	"Characteristics of the sympathetic nervous system",
	"Charcot-Marie-Tooth Syndrome",
	"Charles Bonnet Syndrome",
	"Checkpoints in cell division",
	"Chemical regulators of exocrine pancreatic secretion",
	"Chemotherapy",
	"Chest x-ray changes in heart failure",
	"Chickenpox",
	"Chickenpox",
	"Children's Glasgow Coma Scale",
	"Chlamydia infection",
	"Chlamydia trachomatis",
	"Chlorpromazine mechanism of action",
	"Choking (adults)",
	"Cholecystokinin",
	"Cholera",
	"Cholera",
	"Cholera",
	"Cholestatic jaundice: macrolide (Ddx: rifampicin- yellow secretions, clindamycin- hepatic picture/raised ALT)",
	"Cholesteatoma",
	"Choosing alternative oral hypoglycaemics to GLP-1 analogue/DPP-4 inhibitor in DM patients with pancreatitis with HbA1c >58",
	"Chorioamnionitis",
	"Chronic Kidney Disease",
	"Chronic Kidney Disease",
	"Chronic Sinusitis and Nasal Polyps",
	"Chronic alcoholism",
	"Chronic asthma - peak flow as a measure of disease control",
	"Chronic asthma management in children over 5",
	"Chronic asthma management in children under 5",
	"Chronic fatigue syndrome",
	"Chronic mesenteric ischaemia",
	"Chronic obstructive pulmonary disease (COPD)",
	"Chronic obstructive pulmonary disease (COPD)",
	"Chronic open angle glaucoma",
	"Chronic pancreatitis",
	"Chronic pancreatitis",
	"Chronic urinary retention",
	"Chronotropes and Inotropes",
	"Chylomicrons",
	"Cipro and diarrhoea",
	"Class A personality disorders",
	"Class B personality disorders",
	"Class C personality disorders",
	"Class I anti-arrythmics: Sodium-channel blockers",
	"Class II anti-arrythmics: Beta-blockers",
	"Class III anti-arrythmics: Potassium-channel blockers",
	"Class IV anti-arrythmics: Calcium-channel blockers",
	"Classical conditioning experiments",
	"Classification of T lymphocytes",
	"Classification of epithelia",
	"Classification of memory",
	"Classification of paraproteinaemias",
	"Classification of sensory afferent fibres",
	"Classification of surgical wounds",
	"Classification of thalamic nuclei",
	"Classification of types of channel proteins and carrier proteins",
	"Classifying atypical anti-psychotics",
	"Clavicle fractures",
	"Clavicle fractures",
	"Clinical Features of Head and Neck Cancer",
	"Clinical Features of Tumour Lysis Syndrome",
	"Clinical Pharmacology",
	"Clinical Pharmacology",
	"Clinical Pharmacology",
	"Clinical Pharmacology",
	"Clinical Pharmacology",
	"Clinical features (and causes) of congenital heart block",
	"Clinical features following toxin ingestion in the emergency setting",
	"Clinical features of Huntington's disease",
	"Clinical features of Ischaemic Optic Neuropathy",
	"Clinical features of cerebellar disorder",
	"Clinical features of cirrhosis",
	"Clinical features of developmental disorders of the hip",
	"Clinical features of trisomy syndromes",
	"Clonidine mechanism of action",
	"Clostridium difficile",
	"Clostridium difficile",
	"Clostridium infections",
	"Clotting cascade",
	"Cluster headaches",
	"Co-adminstration of allopurinol and azathioprine",
	"Co-amoxiclav - necrotising enterocolitis",
	"Coagulase negative staphylococcus",
	"Coagulase negative staphylococcus",
	"Coagulation Cascade",
	"Coagulation cascade",
	"Coarctation of aorta",
	"Cocaine mechanism of action",
	"Coeliac disease",
	"Coeliac disease",
	"Coeliac disease (paediatrics)",
	"Coeliac disease microscopic",
	"Colles' fractures",
	"Colon cancer",
	"Colonic motility in Hirschsprung's disease",
	"Colonic polyps",
	"Colonic polyps",
	"Colorectal cancer",
	"Colorectal cancer",
	"Colorectal cancer",
	"Combined Hormonal Contraception",
	"Common drug causes of hypokalaemic metabolic alkalosis",
	"Common genito-urinary infections",
	"Common genitourinary infections",
	"Common peroneal nerve injury",
	"Community-acquired pneumonia - Abx appropriate to CURB",
	"Compartment syndrome",
	"Compartment syndrome",
	"Compartment syndrome",
	"Competitive inhibition",
	"Complex regional pain syndrome",
	"Complications",
	"Complications after relieving outflow obstruction",
	"Complications of blood transfusions",
	"Complications of breast surgery",
	"Complications of central line insertion",
	"Complications of cirrhosis",
	"Complications of hip surgery",
	"Complications of laparoscopic surgery",
	"Complications of parenteral feeding",
	"Complications of streptococcus pyogenes",
	"Complications of streptococcus pyogenes",
	"Complications of thyroid surgery",
	"Complications of thyroid surgery",
	"Complications of total hip replacement",
	"Complications of trisomy syndromes",
	"Components of a lipid bilayer",
	"Components of the Central and Peripheral nervous system",
	"Conduct disorder",
	"Conducting system of the heart",
	"Conductive Hearing loss",
	"Congenital Adrenal Hyperplasia",
	"Congenital Adrenal Hyperplasia",
	"Congenital Cytomegalovirus infection",
	"Congenital Rubella Syndrome",
	"Congenital Toxoplasmosis",
	"Congenital Varicella Zoster Virus",
	"Congenital heart block",
	"Congenital heart disease",
	"Congenital heart disease",
	"Congenital heart disease",
	"Congenital hypothyroidism",
	"Congenital malformations of the gut",
	"Congenital malformations of the heart",
	"Congenital malformations of the male and female reproductive system",
	"Congenital malformations of the urological system",
	"Congestive Cardiac Failure",
	"Conjunctivitis",
	"Conjunctivitis",
	"Connective Tissue - Fibrous Proteins",
	"Constipation",
	"Constipation",
	"Constipation in children",
	"Constrictive pericarditis",
	"Contact Dermatitis",
	"Contra-indications to the oral contraceptive pill",
	"Contraception",
	"Contraception",
	"Contraception injection",
	"Contraceptive implant",
	"Contraceptive implant",
	"Contraction band necrosis",
	"Contraindicated in pregnancy & dosing error",
	"Contraindications To Breastfeeding",
	"Contraindications of b-adrenoceptor antagonist use",
	"Contraindications to Laparoscopic Surgery",
	"Contraindications to combined hormonal contraception",
	"Contraindications to the oral contraceptive pill",
	"Contraindications to vaginal examination in pregnancy",
	"Contraindications to vaginal examination in pregnancy",
	"Control of adrenal medullary secretion",
	"Control of growth hormone secretion",
	"Control of renal vasculature",
	"Control of renal water reabsorption",
	"Control of the Ovarian Cycle",
	"Conversion of PO to TD patch of rivastigmine in Alzheimer's patient",
	"Conversion of drug from SR to MR - Gliclazide",
	"Cord Prolapse",
	"Corneal arcus",
	"Corneal graft rejection",
	"Coronary Artery Bypass",
	"Coronary blood flow",
	"Cortical bone",
	"Cortical regions for hearing",
	"Cortical vascular territories",
	"Corticobulbar tract",
	"Cranial Meninges & Dural Sinuses",
	"Cranial nerve I",
	"Cranial nerve II",
	"Cranial nerve III",
	"Cranial nerve IV",
	"Cranial nerve IX",
	"Cranial nerve V",
	"Cranial nerve VI",
	"Cranial nerve VII",
	"Cranial nerve VIII",
	"Cranial nerve X",
	"Cranial nerve XI",
	"Cranial nerve XII",
	"Cranial nerve foramina",
	"Creutzfeldt-Jakob disease (CJD)",
	"Criteria for assessing capacity in adults",
	"Crohn's disease",
	"Crohn's macroscopic",
	"Croup",
	"Croup",
	"Cruciate ligament injuries",
	"Crystal arthropathies",
	"Cubital tunnel syndrome",
	"Current law on euthanasia and assisted suicide",
	"Cushing's syndrome",
	"Cutaneous considerations of venous and arterial ulcers",
	"Cutaneous considerations of venous and arterial ulcers",
	"Cutaneous features of Tuberous sclerosis",
	"Cutaneous features of neurofibromatosis",
	"Cutaneous features of porphyria cutanea tarda",
	"Cutaneous manifestations of Systemic Sclerosis",
	"Cutaneous manifestations of Systemic lupus erythematosus (SLE)",
	"Cyanotic heart disease",
	"Cyclical mastalgia",
	"Cystic Fibrosis (Paediatrics)",
	"Cystic fibrosis",
	"Cystic fibrosis pathophysiology",
	"Cytochrome P450 enzymes",
	"Cytochrome P450 enzymes",
	"Cytogenetic Abnormalities",
	"Cytogenetics",
	"DKA- titrating insulin vs ketone level based on changes in HCO3/pH/BM",
	"Dapagliflozin",
	"De Quervain's tenosynovitis",
	"Death Confirmation",
	"Deep Vein Thrombosis (DVT)",
	"Deep Vein Thrombosis (DVT)",
	"Definition of osmolality vs osmolarity",
	"Degenerative Joint Disease",
	"Dehydration in Gastroenteritis (paediatrics)",
	"Delayed puberty",
	"Delayed puberty",
	"Delirium",
	"Delirium",
	"Delirium tremens",
	"Delirium tremens",
	"Delirium tremens",
	"Delusions",
	"Dementia",
	"Dementia with Lewy bodies",
	"Dementia with Lewy bodies",
	"Dementia with Lewy bodies",
	"Dendritic Cell properties",
	"Depression",
	"Depression",
	"Depression",
	"Depression",
	"Depression in children - only fluoxetine is licensed",
	"Deprivation of Liberty",
	"Derangements of albumin",
	"Dermatofibroma",
	"Dermatomes",
	"Dermatomyositis",
	"Dermatomyositis features",
	"Descending motor tracts",
	"Descriptive Psychopathology",
	"Determinants of glomerular filtration",
	"Development of female reproductive system",
	"Development of foetal circulation",
	"Development of limb buds",
	"Development of male reproductive system",
	"Development of pharyngeal arches",
	"Development of pharyngeal pouches",
	"Development of somites",
	"Development of spinal cord",
	"Development of the Kidneys",
	"Development of the Kidneys",
	"Development of the Respiratory System",
	"Development of the bladder",
	"Development of the body cavities and the diaphragm",
	"Development of the female reproductive system",
	"Development of the fetal circulation",
	"Development of the foregut",
	"Development of the hindgut",
	"Development of the limb buds",
	"Development of the lungs",
	"Development of the male reproductive system",
	"Development of the midgut",
	"Development of the pacemaker and conduction system",
	"Development of the spinal cord",
	"Development of the vertebral column",
	"Development of valves and outflow tracts",
	"Developmental disorders of the hip",
	"Developmental milestones - fine motor and vision",
	"Developmental milestones - gross motor",
	"Developmental milestones - hearing, communication and language",
	"Diabetes - starting another oral hypoglycaemic after metformin",
	"Diabetes - starting another oral hypoglycaemic after metformin",
	"Diabetes Insipidus",
	"Diabetes Insipidus",
	"Diabetes Mellitus",
	"Diabetes in pregnancy",
	"Diabetes with evidence of renal impairment - start ACEi regardless of BP",
	"Diabetic Ketoacidosis",
	"Diabetic foot",
	"Diabetic kidney microscopic",
	"Diabetic neuropathy",
	"Diabetic neuropathy",
	"Diabetic retinopathy",
	"Diabetic retinopathy",
	"Diagnosis",
	"Diagnosis of primary immunodeficiency syndromes",
	"Differences between fibrous and globular proteins",
	"Differences in blood flow through in the upright lung",
	"Different types of beta blockers",
	"Differential Diagnosis of Mass in Liver",
	"Differential for cavitating lung lesions",
	"Differentials of Nausea and Vomiting in Oncology",
	"Differentials of Red Eye",
	"Differentials of Shortness of Breath in oncology",
	"Differentials of Shortness of Breath in oncology",
	"Differentials of Vomiting in Children",
	"Differentials of acute stress reaction",
	"Differentials of confusion in oncology",
	"Differentials of diplopia (ophthalmology)",
	"Differentials of diplopia (ophthalmology)",
	"Differentials of dystonia",
	"Differentials of ejection systolic murmur",
	"Differentials of gradual visual loss",
	"Differentials of pan-systolic murmur",
	"Differentials of splenomegaly",
	"Differentiation of pluripotent haematopoietic cells",
	"Digestion and absorption of carbohydrates",
	"Digestion and absorption of fat",
	"Digital Subtraction Angiography and Subarachnoid Haemorrhage",
	"Digoxin",
	"Digoxin - xanthopsia",
	"Digoxin levels",
	"Digoxin poisoning",
	"Digoxin toxicity - chlortalidone (thiazide-like diuretics)",
	"Dilated cardiomyopathy",
	"Dilution of a drug such that soution does not exceed certain concentration - Vancomycin",
	"Direct Oral Anticoagulant mechanism of action",
	"Direct and indirect inguinal hernias",
	"Direct oral anticoagulants",
	"Disclosing in the public interest",
	"Disease resulting from immunological tolerance breakdown",
	"Disorders of Vasopressin secretion",
	"Disorders of growth hormone secretion",
	"Disseminated intravascular coagulation (DIC)",
	"Disseminated intravascular coagulation (DIC)",
	"Distal forearm fractures",
	"Distinguishing between Advanced Statements and Advanced Decisions",
	"Distinguishing between Advanced Statements and Advanced Decisions",
	"Distinguishing between primary, secondary tertiary, quaternary protein structures",
	"Distinguishing between primary, secondary tertiary, quaternary protein structures",
	"Distinguishing the primary and secondary immune responses",
	"Distribution of body water",
	"Diuretic use in acute heart failure",
	"Diverticular disease",
	"Diverticulosis",
	"Divisions of the cerebellum",
	"Divisions of the cerebellum",
	"Doctrine of Double effect",
	"Donepezil",
	"Dorsal column tract",
	"Dose to be given in 24 hours - Magnesium in Eclampsia",
	"Dosing error & BM suppresion",
	"Dosing error & angioedema",
	"Dosing error & drugs causing hyperkalemia",
	"Dosing error & drugs causing hyponatraemia",
	"Dosing error & drugs causing hyponatremia",
	"Dosing error & drugs that prolong QT",
	"Dosing error & drugs worsening Parkinson’s",
	"Double dose of levonorgestrel as EC if high BMI or taking p450 inducer",
	"Down Syndrome Screening",
	"Down syndrome (Genetics)",
	"Down's Syndrome",
	"Down's Syndrome",
	"Down's Syndrome Screening",
	"Drug Antagonists at the GABA receptor",
	"Drug Classes",
	"Drug Classes for asthma",
	"Drug Interactions",
	"Drug Interactions with Warfarin",
	"Drug Receptors",
	"Drug causes of digoxin toxicity",
	"Drug contraindications for G6PD & asthma",
	"Drug contraindications for G6PD & asthma",
	"Drug eruptions",
	"Drug receptor antagonism",
	"Drugs associated with congenital heart defect and contraindicated in breastfeeding",
	"Drugs causing confusion and bradycardia",
	"Drugs causing diarrhoea & dosing error",
	"Drugs causing drowsiness & constipation",
	"Drugs causing weight gain & drowsiness",
	"Drugs stimulating histamine release from mast cells",
	"Drugs that reduce salivary and airway secretions",
	"Drugs to stop before surgery",
	"Drugs to stop before surgery",
	"Drugs used to treat leprosy",
	"Drugs used to treat leprosy",
	"Drugs used to treat tuberculosis",
	"Duchenne muscular dystrophy (genetics)",
	"Duodenal atresia",
	"Duodenum",
	"Dupuytren's contracture",
	"Duration of anticoagulation in DVT/PE",
	"Dysmenorrhoea",
	"Dyspepsia",
	"ECG",
	"ECG set up",
	"ESBL-producing gram-negative infections",
	"Early gut formation",
	"Eclampsia",
	"Ectopic pregnancy",
	"Ectopic pregnancy",
	"Effect of ANP on the kidney",
	"Effect of histamine receptors on secretory function",
	"Effect of loop diuretics on calcium excretion",
	"Effect of the P450 enzyme system on contraceptive pills",
	"Effect of thiazide diuretics on calcium excretion",
	"Effect of thiazide diuretics on calcium excretion",
	"Eisenmenger Syndrome",
	"Ejection systolic murmurs",
	"Electrolyte abnormalities in the context of Digoxin Toxicity",
	"Electron transport chain",
	"Ellaone",
	"Ellaone",
	"Emergency Contraception",
	"Emergency Management of Acute Asthma Exacerbation",
	"Emergency Management of Acute Coronary Syndrome",
	"Emergency Management of Acute Exacerbation of COPD",
	"Emergency Management of Acute angle closure glaucoma",
	"Emergency Management of Anaphylaxis",
	"Emergency Management of Atrial Fibrillation",
	"Emergency Management of Carbon Monoxide poisoning",
	"Emergency Management of Cardiac Tamponade",
	"Emergency Management of Cardiac Tamponade",
	"Emergency Management of Diabetic Ketoacidosis",
	"Emergency Management of Diabetic Ketoacidosis",
	"Emergency Management of Diabetic Ketoacidosis",
	"Emergency Management of Diabetic Ketoacidosis",
	"Emergency Management of Ethylene Glycol Poisoning",
	"Emergency Management of Extradural haemorrhage",
	"Emergency Management of Hyperosmolar Hyperglycaemic State (HHS)",
	"Emergency Management of Metabolic acidosis with raised anion gap",
	"Emergency Management of Pericarditis",
	"Emergency Management of Pneumothorax",
	"Emergency Management of Pulmonary Embolism",
	"Emergency Management of Pulmonary Embolism",
	"Emergency Management of Status Epilepticus",
	"Emergency Management of Supraventricular tachycardia",
	"Emergency Management of Supraventricular tachycardia",
	"Emergency Management of Tension Pneumothorax",
	"Emergency Management of Torsades de pointes",
	"Emergency Management of Torsades de pointes",
	"Emergency Management of Upper GI bleed",
	"Emergency Management of Ventricular Tachycardia",
	"Emergency Management of myxoedema coma",
	"Emergency management of Acute Kidney Injury(AKI)",
	"Emergency management of Addisonian crisis",
	"Emergency management of Addisonian crisis",
	"Emergency management of Encephalitis",
	"Emergency management of Status Epilepticus",
	"Emergency management of acute pulmonary oedema",
	"Emergency management of acute pulmonary oedema",
	"Emergency management of addisonian crisis",
	"Emergency management of aspirin overdose",
	"Emergency management of aspirin overdose",
	"Emergency management of blackouts",
	"Emergency management of digoxin poisoning",
	"Emergency management of hypoglycaemia",
	"Emergency management of hypoglycaemia",
	"Emergency management of pheochromocytoma (acute)",
	"Emergency management of suspected acute spinal cord compression",
	"Emergency management of suspected acute spinal cord compression",
	"Emergency management of suspected acute spinal cord compression",
	"Emergency management of thyrotoxic storm",
	"Encephalitis",
	"End of Life Care Medications",
	"End of Life Care Medications",
	"End-of-life agitation",
	"Endocrine function of the kidney",
	"Endometrial cancer",
	"Endometriosis",
	"Endophthalmitis",
	"Endotoxins and exotoxins",
	"Enhancers",
	"Enteroviruses",
	"Eosinophil properties",
	"Eosinophilic granulomatosis with polyangiitis (Churg-Strauss)",
	"Epididymo-orchitis",
	"Epidural anaesthesia",
	"Epilepsy Management",
	"Epilepsy and Driving",
	"Epilepsy in pregnancy",
	"Epilepsy syndromes",
	"Episcleritis and Scleritis",
	"Epistaxis",
	"Epistaxis",
	"Eponymous signs in the surgical abdomen",
	"Eponymous syndromes",
	"Erectile Dysfunction",
	"Ergot alkaloid mechanism of action",
	"Errors",
	"Errors",
	"Erythema Nodosum",
	"Erythema multiforme",
	"Erythroderma",
	"Essential thrombocytosis",
	"Essential tremor",
	"Estimating Glomerular Filtration Rate",
	"Estimating medication doses in children",
	"Eukaryotic promoters",
	"Euthanasia",
	"Evaluation of a diagnostic test",
	"Ewing's sarcoma",
	"Examples of G protein-coupled receptor",
	"Excitatory vs inhibitory cell types of the cerebellum",
	"Extensor Compartments",
	"External ear",
	"Extracellular matrix components",
	"Extradural Haemorrhage",
	"Extradural haematoma",
	"Extrapyramidal tracts",
	"FSGS microscopic",
	"Face—Deep Layer",
	"Face—Superficial Layer",
	"Facial Nerve Palsy",
	"Facilitate vs active diffusion",
	"Factors affecting blood flow to the skin circulation",
	"Factors affecting fetal growth",
	"Factors affecting foetal growth",
	"Factors that determine direction of molecule flow across cell membrane",
	"Factors that increase cerebral blood flow",
	"Familial Mediterranean fever",
	"Fat Necrosis of the breast",
	"Fat embolism",
	"Fat-soluble vitamins",
	"Features of Creutzfeldt-Jakob disease",
	"Features of Reactive Arthritis",
	"Features of Tetracyclines",
	"Features of alpha helix, beta sheet and loops",
	"Features of dehydration in gastroenteritis",
	"Features of enteric arthropathy",
	"Features of epithelia",
	"Features of hyperthyroidism",
	"Features of hypothyroidism",
	"Features of inflammation",
	"Features of innocent murmurs in children",
	"Features of myositis ossificans",
	"Features of psoriatic arthritis",
	"Features of the parasympathetic nervous system",
	"Febrile convulsions",
	"Febrile seizure",
	"Felty Syndrome",
	"Female Genital Mutilation (FGM)",
	"Female Reproductive Anatomy",
	"Female urethra",
	"Femoral Canal",
	"Femoral hernias",
	"Femoral nerve",
	"Fertility",
	"Fever in the returning traveller",
	"Fibroadenoma of the breast",
	"Fibrocystic disease of the breast",
	"Fibroids",
	"Fibroids",
	"Fibromuscular dysplasia",
	"Fibromyalgia",
	"Fibula",
	"Fibular nerves",
	"First Stage of Labour",
	"First order kinetics",
	"Fissure in ano",
	"Fitz Hugh Curtis Syndrome",
	"Fluid and electrolyte absorption in the GI tract",
	"Fluid deprivation tests",
	"Fluid prescribing",
	"Fluid prescribing",
	"Fluid rehydration in children",
	"Fluoroscopy",
	"Foetal Alcohol Syndrome",
	"Foetal Circulation",
	"Folliculitis and related conditions",
	"Foot drop",
	"Foot fractures",
	"Foot: Dorsal Muscles",
	"Foot: Nerves",
	"Foot: Plantar Muscles—1st Layer",
	"Foot: Plantar Muscles—2nd Layer",
	"Foot: Plantar Muscles—3rd Layer",
	"Foot: Plantar Muscles—4th Layer",
	"Foot: Vasculature",
	"Forced expiratory volume in 1 second (FEV1)",
	"Forced vital capacity",
	"Forearm: Muscles—Deep Extensors",
	"Forearm: Muscles—Deep Flexors",
	"Forearm: Muscles—Superficial Extensors",
	"Forearm: Muscles—Superficial Flexors",
	"Forearm: Nerves",
	"Forearm: Vessels",
	"Foreign body in the nose",
	"Foreign object swallowed",
	"Foreign object swallowed",
	"Formal thought disorder",
	"Formation of Bradykinin",
	"Formation of bile acids and bile salts",
	"Formation of heart chambers",
	"Formation of seminal fluid",
	"Formation of seminal fluid",
	"Formation of stomach acid",
	"Formation of the bilaminar disc",
	"Formation of the bilaminar disk",
	"Formation of the primitive streak",
	"Fracture Healing",
	"Fracture of the elbow joint",
	"Fracture of the elbow joint",
	"Fractured neck of femur",
	"Fractured neck of femur",
	"Fragile X syndrome",
	"Fraser Guidelines",
	"Frequency of gentamicin monitoring- gentamicin nomogram",
	"Friedreich's ataxia",
	"Frontotemporal dementia",
	"Frozen shoulder",
	"Full blood count abnormalities",
	"Fungi",
	"Furosemide- increased risk of calcium stones",
	"GBS positive - intrapartum benzylpenicillin",
	"GLP-1 Agonists",
	"GLP-1 and GLP-2",
	"GTN- headache",
	"GTN- headache",
	"Galactorrhoea in men",
	"Gallbladder carcinoma",
	"Gallbladder carcinoma",
	"Gallstone disease",
	"Ganglion",
	"Gas Gangrene",
	"Gas Gangrene",
	"Gaseous Exchange And Transport",
	"Gastric cancer",
	"Gastric secretion",
	"Gastric structure and function",
	"Gastric-inhibitory polypeptide",
	"Gastrin",
	"Gastro-intestinal malabsorption",
	"Gastro-oesophageal reflux disease",
	"Gastro-oesophageal reflux disease",
	"Gastro-oesophageal reflux in children",
	"Gastroenteritis",
	"Gastroenteritis",
	"Gastroesophageal reflux disease in infants",
	"Gastrointestinal glucose absorption",
	"Gastrointestinal infections and pathogens",
	"Gastroparesis",
	"Gastrulation",
	"General features of the human genome",
	"Generalised pruritis",
	"Generalised seizures",
	"Generation of ATP by glycolysis",
	"Generation of ATP by glycolysis",
	"Genetic Calculations",
	"Genetic Concepts",
	"Genetic Diseases",
	"Genetic Inheritance",
	"Genetic Mechanisms",
	"Genetic pathophysiology of Severe Combined Immunodeficiency (SCID)",
	"Genetic syndromes and Cancer",
	"Genetics of Down syndrome",
	"Genital Herpes",
	"Genital candidiasis",
	"Genital candidiasis",
	"Genital prolapse",
	"Genital warts",
	"Genital warts",
	"Gentamicin - renal function before giving",
	"Gestational Diabetes",
	"Gestational Diabetes",
	"Giant Cell Arteritis",
	"Giardiasis",
	"Gilbert's Syndrome",
	"Glandular fever",
	"Glandular fever",
	"Gliclazide - hypoglycaemia",
	"Glomerular Filtration Rate",
	"Glomerular Filtration Rate",
	"Glomerular Filtration Ratio",
	"Glomerular permeability",
	"Glomerulonephritis",
	"Glomerulus structure",
	"Glucocorticoids",
	"Glucose reabsorption",
	"Gluteal Region: Muscles",
	"Gluteal Region: Muscles",
	"Gluteal Region: Nerves",
	"Gluteal Region: Vasculature",
	"Glycogenesis",
	"Glycogenolysis",
	"Goitre",
	"Golgi tendon organ properties",
	"Goodpasture's syndrome",
	"Gout",
	"Gout - allopurinol with NSAID cover",
	"Gout flare",
	"Gram positive bacilli",
	"Gram staining",
	"Granulocyte colony-stimulating factor",
	"Granulomatosis with polyangiitis (Wegener's Granulomatosis)",
	"Granulomatosis with polyangiitis (Wegener's Granulomatosis)",
	"Gravidity and parity",
	"Great vessels of the heart",
	"Greenstick fracture",
	"Grey baby syndrome",
	"Groin lumps",
	"Group B Streptococcus infection",
	"Guillain-Barré Syndrome",
	"Gynaecomastia",
	"H. Pylori",
	"H. pylori",
	"H2 antagonists",
	"HDL",
	"HELLP Syndrome",
	"HIV and pregnancy",
	"HIV mother to child transmission",
	"HIV related tumours",
	"HLAB27 and Ank Spond",
	"Haemangioma",
	"Haematological Malignancies",
	"Haematopoiesis",
	"Haematuria",
	"Haemoglobin",
	"Haemoglobin A",
	"Haemoglobinopathies",
	"Haemolytic Uraemic Syndrome",
	"Haemolytic anaemia",
	"Haemolytic disease of the newborn",
	"Haemophilia",
	"Haemophilia",
	"Haemophilias",
	"Haemopytsis differentials",
	"Haemorrhagic stroke",
	"Haemorrhagic stroke",
	"Haemorrhoids",
	"Hallmarks of inflammation",
	"Haloperidol mechanism of action",
	"Halothane side effects",
	"Halothane toxicity",
	"Hamate fractures",
	"Hand: Innervation Of Intrinsic Muscles",
	"Hand: Muscles—Deep",
	"Hand: Muscles—Superficial",
	"Hand: Nerves",
	"Hand: Vasculature",
	"Head Injury - Imaging Criteria",
	"Head Trauma",
	"Head and Neck Neoplasia",
	"Headache",
	"Hearing, speech and language milestones",
	"Heart Block",
	"Heart Block",
	"Heart failure",
	"Heart failure",
	"Hemiballismus pathophysiology",
	"Henderson–Hasselbalch equation",
	"Henoch Schonlein Purpura (paediatrics)",
	"Henoch-Schonlein purpura",
	"Henoch-Schonlein purpura (Dermatology)",
	"Hepatic circulation",
	"Hepatitis B in pregnancy",
	"Hepatitis viruses",
	"Hepatitis viruses",
	"Hepatitis viruses",
	"Hepatocellular Carcinoma",
	"Hepatocellular Carcinoma",
	"Hepatocellular Carcinoma",
	"Herd Immunity",
	"Hereditary haemochromatosis",
	"Hereditary haemorrhagic telangiectasia",
	"Hereditary spastic paraparesis",
	"Heroin withdrawal",
	"Herpes Zoster Ophthalmicus",
	"Herpes Zoster Ophthalmicus (importance of nasal involvement)",
	"Herpes simplex keratitis",
	"Herpes viruses",
	"Hesselbach's Triangle",
	"Hiatus hernia management",
	"High INR",
	"Hirsutism",
	"Histamine",
	"Histamine receptos and smooth muscle relaxation",
	"Hoarseness",
	"Hodgkin's lymphoma",
	"Hodgkin's lymphoma",
	"Hormonal Control Of Glucose Metabolism",
	"Hormonal control of calcium",
	"Hormonal control of spermatogenesis",
	"Hormone Biosynthesis",
	"Hormone replacement therapy",
	"Hormone replacement therapy",
	"Hormone replacement therapy",
	"Hormones during pregnancy",
	"Hormones in the Ovarian Cycle",
	"Hormones of the anterior pituitary gland",
	"Hormones of the anterior pituitary gland",
	"Hormones of the posterior pituitary gland",
	"Horner's syndrome",
	"Horner's syndrome",
	"Horner's syndrome",
	"Horner's syndrome",
	"Horseshoe kidney",
	"Hounsfield units",
	"How antibiotics affect translation",
	"Human chorionic gonadotropin (hCG)",
	"Huntington disease pathophysiology",
	"Hydrocele",
	"Hydrocele (Urology)",
	"Hydrocephalus (paediatrics)",
	"Hydrogen ion secretion at the distal tubule",
	"Hydronephrosis - gross",
	"Hydroxychloroquine",
	"Hyperaldosteronism and Conn's syndrome",
	"Hyperaldosteronism and Conn's syndrome",
	"Hypercalcaemia",
	"Hypercholesterolaemia",
	"Hyperemesis gravidarum",
	"Hyperkalaemia",
	"Hypermobility syndrome",
	"Hypernatraemia",
	"Hyperparathyroidism",
	"Hyperparathyroidism",
	"Hyperphosphataemia",
	"Hyperprolactinaemia",
	"Hyperprolactinaemia & dosing error",
	"Hypersensitivity reactions",
	"Hypertension",
	"Hypertension without proteinuria in pregnancy",
	"Hypertension without proteinuria in pregnancy",
	"Hypertensive retinopathy",
	"Hyperthyroidism",
	"Hyperthyroidism",
	"Hypertrophic cardiomyopathy",
	"Hyperuricaemia",
	"Hypo-K increases risk of digoxin toxicity",
	"Hypoalbuminaemia",
	"Hypocalcaemia",
	"Hypocalcaemia",
	"Hypoglycaemia",
	"Hypokalaemia",
	"Hypokalaemia",
	"Hypokalaemia",
	"Hypomagnasaemia",
	"Hyponatraemia",
	"Hypoparathyroidism",
	"Hypoparathyroidism pathophysiology",
	"Hypophosphataemia",
	"Hypotension During Surgery",
	"Hypotestosteronism",
	"Hypotestosteronism",
	"Hypothermia",
	"Hypothermia",
	"Hypothyroidism",
	"Hypothyroidism",
	"Hypoxic ischaemic encephalopathy",
	"IUD",
	"Iatrogenic diarrhoea and constipation",
	"Idiopathic Intracranial Hypertension",
	"Idiopathic Intracranial Hypertension",
	"Idiopathic Intracranial Hypertension",
	"IgA nephropathy",
	"IgG4 related disease",
	"Immune Tolerance",
	"Immune thrombocytopenic purpura",
	"Immune thrombocytopenic purpura",
	"Immunodeficiency",
	"Immunoglobulins and mast cell degranulation",
	"Impaired fasting glucose",
	"Impaired glucose tolerance",
	"Impetigo",
	"Impetigo",
	"Impetigo",
	"Impetigo",
	"Important cortical regions",
	"In-Vitro Fertilisation",
	"Indications for CT head in the Emergency Setting",
	"Indications for CT in head injury",
	"Indications for TIPSS",
	"Indications for combined anti-retroviral therapy in HIV",
	"Indirect antagonist",
	"Induction of anaesthesia",
	"Induction of labour",
	"Infectious mononucleosis treated with amoxicillin/ampicillin - macular papular rash",
	"Infective Endocarditis",
	"Infective Endocarditis Pathology",
	"Infective Gastroenteritis",
	"Inferior vena cava filter",
	"Infertility",
	"Infertility",
	"Infertility",
	"Influenza",
	"Influenza virus",
	"Infratemporal fossa",
	"Inguinal Canal",
	"Inguinal Canal",
	"Inherited thrombophilias",
	"Inhibition of H2 receptors in the gut",
	"Initial treatment for MDD - if response not adequte within 4 weeks, can titrate dose of SSRI up",
	"Innervation of the anal sphincter",
	"Innervation of the respiratory system",
	"Inotropy and Cardiac Glycosides",
	"Input to cerebellar Purkinje cells",
	"Insulin sick day rule",
	"Interleukin control of B cell proliferation and modulation",
	"Internuclear ophthalmoplegia",
	"Interpretation of Bishop score",
	"Interpretation of Troponin rise in the Emergency Setting",
	"Interpretation of blood results in bleeding disorders",
	"Interpretation of eclampsia blood results and treatment dose of Mg SO4",
	"Interpretation of foetal blood sampling",
	"Interpreting APGAR score",
	"Interpreting UTI (Urine dipstick and MCS positive, susceptible to Nitro and Tri) + U/E showing renal failure eGFR < 30: use normal dose (1st 3 days)",
	"Interventional studies",
	"Intestinal absorption of calcium",
	"Intra-ocular foreign body",
	"Intra-uterine device",
	"Intra-uterine device",
	"Intra-uterine system",
	"Intra-uterine system",
	"Intracellular signalling and HER2 receptors",
	"Intracranial Venous Thrombosis",
	"Intracranial haemorrhage",
	"Intraperitoneal and retroperitoneal organs",
	"Intrauterine Contraception",
	"Intrauterine device",
	"Intrauterine system",
	"Intravenous contrast reactions",
	"Intravenous fluid resuscitation",
	"Intravenous fluid resuscitation",
	"Intravenous fluid resuscitation",
	"Intraventricular haemorrhage",
	"Intrinsic factor",
	"Intussusception",
	"Intussusception",
	"Inulin clearance",
	"Inversion of the uterus",
	"Inversion of the uterus",
	"Investigation",
	"Investigations in depression",
	"Ion channel pharmacology",
	"Ionising radiation",
	"Ipratropium bromide",
	"Iron deficiency anaemia",
	"Iron deficiency anaemia",
	"Iron deficiency anaemia",
	"Irregular Menstrual bleeding",
	"Irritable Bowel Syndrome (IBS)",
	"Ischaemic Stroke",
	"Isolated cranial nerve palsies affecting the eye",
	"Isolated cranial nerve palsies affecting the eye",
	"Isoprenaline administration",
	"Issues of parental responsibility",
	"Issues of parental responsibility",
	"JS Mill's Harm Principle",
	"Jarisch-Herxheimer Reaction",
	"Jaundice",
	"Jaundice (paediatrics)",
	"Jejunum and Ileum",
	"Jugular foramen syndrome",
	"Jugular veins",
	"Justifications for withdrawing and withholding treatment",
	"Juvenile dermatomyositis",
	"Juvenile dermatomyositis",
	"Juvenile idiopathic arthritis",
	"Kawasaki disease",
	"Kayser-Fleischer rings",
	"Keloid scar",
	"Keratitis",
	"Keratoacanthoma",
	"Keratoacanthoma",
	"Ketosis",
	"Key principles of MCA (Mental Capacity Act)",
	"Key principles of MCA (Mental Capacity Act)",
	"Kinase linked receptors",
	"Kleihauer test",
	"Klinefelter syndrome (Genetics)",
	"Krebs cycle",
	"LMWH - no monitoring parameter is available (e.g platelets, INR)",
	"Labour",
	"Lacrimal sac infection",
	"Lactational Breast abscess",
	"Lactational mastitis - PO flucloxacillin if unresolving",
	"Lactic acidosis",
	"Lactic acidosis",
	"Lambert-Eaton Myasthenic Syndrome (LEMS)",
	"Large Bowel Obstruction",
	"Lasting power of attorney, IMCA, and Court of Protection",
	"Late Onset Sepsis of a Newborn",
	"Lateral epicondylitis",
	"Laxatives",
	"Layers of the scalp",
	"Left iliac fossa mass",
	"Left iliac fossa pain",
	"Left lower lobe collapse",
	"Left sided superior vena cava",
	"Left sided superior vena cava",
	"Left upper lobe collapse",
	"Left upper quadrant masses",
	"Left upper quadrant pain",
	"Leg: Muscles—Anterior Compartment",
	"Leg: Muscles—Lateral Compartment",
	"Leg: Muscles—Posterior Compartment",
	"Leg: Nerves",
	"Leg: Vasculature",
	"Legal duty of care",
	"Legal duty vs legal defence",
	"Legal requirements for valid patient consent",
	"Legionella",
	"Leprosy",
	"Lesion localisation in aphasia",
	"Lesion sites in movement disorders",
	"Lesions Of The Central Nervous System",
	"Lesions causing aphasia",
	"Lesions causing memory dysfunction",
	"Lesions of the central vs peripheral nervous system",
	"Less common Hernias",
	"Leukaemia",
	"Levator palpebrae superioris",
	"Levodopa",
	"Levodopa",
	"Levonelle",
	"Levonelle",
	"Libido",
	"Lichen planus",
	"Lichen sclerosus",
	"Life span of RBCs, WBCs and platelets",
	"Light near dissociation",
	"Lines seen on chest x-rays",
	"Link reaction",
	"Lipid absorption in the small intestine",
	"Lipid lowering agents",
	"Lipohaemarthrosis",
	"Lipohaemarthrosis",
	"Lipolytic enzymes of the pancreas",
	"Lisfranc Injury",
	"Lisfranc Injury",
	"Listeria Monocytogenes in pregnancy",
	"Lithium - Indapamide",
	"Lithium and pregnancy",
	"Lithium dosing - check levels after 12 hours",
	"Lithium toxicity",
	"Lithium toxicity",
	"Liver Cirrhosis",
	"Liver failure",
	"Local anaesthetic toxicity",
	"Locked in syndrome Pathophysiology",
	"Locked-in syndrome",
	"Long QT syndrome",
	"Long QT syndrome",
	"Long QT-Syndrome",
	"Long thoracic nerve damage",
	"Loop diuretic and heart failure",
	"Loperamide",
	"Low molecular weight heparin",
	"Lower GI Bleeding",
	"Lower motor neuron lesions",
	"Lower urinary tract symptoms (LUTS) in men (including bladder outflow obstruction)",
	"Lumbosacral Plexus",
	"Lumbosacral Plexus",
	"Lung Cancer",
	"Lung Cancer",
	"Lung Cancer",
	"Lung Compliance",
	"Lung Function Tests",
	"Lung Nodules",
	"Lung abscess",
	"Lung abscess",
	"Lung structure",
	"Lung vasculature",
	"Lung volumes",
	"Lupus immunology",
	"Lyme Disease",
	"Lyme Disease",
	"Lymphogranuloma Venereum",
	"MAO inhibitors",
	"MHC 1 vs MHC II and different cells they present to (clinical consequence: Graft rejection?)",
	"MRI in Pregnancy",
	"MRI safety",
	"Macrocephaly",
	"Macrocytosis",
	"Macrophages properties",
	"Maisonneuve injury",
	"Maisonneuve injury",
	"Malabsorption syndromes",
	"Malaria",
	"Male urethra",
	"Malignant Melanoma",
	"Malignant Phyllodes tumour",
	"Malignant hyperthermia",
	"Malignant hyperthermia",
	"Malrotation (paediatrics)",
	"Mammary glands",
	"Management of Kawasaki disease",
	"Management of a choking child",
	"Management of acute stridor",
	"Management of atrial flutter",
	"Management of carotid artery stenosis",
	"Management of decompensated chronic liver disease",
	"Management of foreign body in the upper aerodigestive tract",
	"Management of head injury in children",
	"Management of head trauma",
	"Management of head trauma",
	"Management of head trauma",
	"Management of pregnancy at 41 weeks",
	"Management of pulseless electrical activity",
	"Management of urinary incontinence",
	"Management of wound dehiscence",
	"Marfan syndrome (Genetics)",
	"Marfan's Syndrome",
	"Markers of underhydration and overhydration",
	"Mast Cells properties",
	"Mast cell degranulation",
	"Mastectomy on Chest Xrays",
	"Mastitis",
	"Maternal Physiology",
	"Maternal risk factors for congenital heart disease",
	"Meaning of semi-conservative DNA replication",
	"Measles",
	"Measles",
	"Measles",
	"Measurement bias",
	"Measures of association",
	"Measuring glomerular filtration rate",
	"Mebeverine",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action",
	"Mechanism Of Action for Lowering Blood Pressure",
	"Mechanism Of Action of Acamprosate",
	"Mechanism Of Action of Anaesthetic Drugs",
	"Mechanism Of Action of Carbemazepine",
	"Mechanism Of Action of Cocaine",
	"Mechanism Of Action of Eplerenone",
	"Mechanism Of Action of Glycopeptides",
	"Mechanism Of Action of Loop Diuretics",
	"Mechanism Of Action of Macrolides",
	"Mechanism Of Action of Penicillin",
	"Mechanism Of Action of Propanolol",
	"Mechanism Of Action of Sulphonamides",
	"Mechanism Of Action of Theophylline",
	"Mechanism Of Action of Zopiclone",
	"Mechanism Of Action of amphetamines",
	"Mechanism Of Action of cholestyramine",
	"Mechanism Of Action of polymixins",
	"Mechanism Of Action of tetracycline antibiotices",
	"Mechanism Of Action of thiazides in hypertension",
	"Mechanism Of Action of thiazides in hypertension",
	"Mechanism of Chronic Granulomatous Disease",
	"Mechanism of DNA replication",
	"Mechanism of Gabapentin in the treatment of pain",
	"Mechanism of MAO inhibition",
	"Mechanism of PCR",
	"Mechanism of action in muscarinic antagonism",
	"Mechanism of action of acetazolamide",
	"Mechanism of action of anti-muscarinic agents in glaucoma",
	"Mechanism of action of antidepressants",
	"Mechanism of action of competitive antagonists",
	"Mechanism of action of ipratropium",
	"Mechanism of action of montekulast",
	"Mechanism of action of oestrogen in the combined oral contraceptive pill",
	"Mechanism of action the progestogen-only pill",
	"Mechanism of anti-thrombotic effect of aspirin",
	"Mechanism of cytotoxic T lymphocyte action in infected cell destruction",
	"Mechanism of dry cough following ACE-inhibitor use",
	"Mechanism of endocytosis",
	"Mechanism of exocytosis",
	"Mechanism of long-term potentiation",
	"Mechanism of long-term potentiation¶##Linked Recalls",
	"Mechanism of microarray analysis",
	"Mechanism of pain sensation",
	"Mechanism of platelet sensitivity to aspirin",
	"Mechanism of platelet sensitivity to aspirin",
	"Mechanism of referred pain",
	"Mechanism of stereocilia",
	"Mechanism of the basilar membrane",
	"Mechanism of transcription",
	"Mechanism of translation",
	"Mechanisms Of Fertilisation",
	"Mechanisms of anti-microbial resistance",
	"Mechanisms of long-term depression",
	"Meckel's Diverticulum",
	"Meconium",
	"Meconium aspiration",
	"Meconium aspiration syndrome",
	"Meconium ileus",
	"Medial epicondylitis",
	"Medical TOP - BP monitoring for 3 hours afterwards",
	"Medical causes of the acute abdomen",
	"Medical management of peripheral vascular disease - clopidogrel + statin",
	"Medical management of peripheral vascular disease - clopidogrel + statin",
	"Medical third nerve palsy",
	"Medically unexplained symptoms",
	"Medication overuse headaches",
	"Melanocytic naevi",
	"Melanosis coli",
	"Membrane Processes",
	"Membrane permeability in drug absorption",
	"Membranes of the vestibulocochlear system",
	"Membranous nephropathy microscopic",
	"Meniere's disease",
	"Meningioma",
	"Meningitis",
	"Meningitis",
	"Meningitis",
	"Meningitis and Encephalitis",
	"Meningococcal infection",
	"Meningococcal infection",
	"Meniscal tear",
	"Menopause",
	"Menopause",
	"Menopause",
	"Menorrhagia",
	"Menstrual Cycle",
	"Meralgia Paresthetica",
	"Mesenteric adenitis",
	"Mesenteric adenitis",
	"Mesentery structure",
	"Metabolic actions of cortisol",
	"Metabolic alkalosis",
	"Metabolic conditions",
	"Metformin - lactic acidosis",
	"Metformin uptitration if HbA1c >58",
	"Methadone",
	"Methanol poisoning",
	"Methotrexate",
	"Methotrexate",
	"Methotrexate",
	"Methotrexate",
	"Methotrexate",
	"Methyldopa mechanism of action",
	"Methylphenidate choose 3 things to check - BP, weight and height",
	"Metronidazole and anaerobic cells",
	"Metronidazole and anaerobic cells",
	"Metronidazole and anaerobic cells",
	"Metronidazole and anaerobic cells",
	"Microbiology of tuberculosis",
	"Microcirculation and Tissue Fluid Exchange",
	"Microcytic Anaemia",
	"Microcytic Anaemia",
	"Microscopic Polyangitis",
	"Microscopic TB",
	"Micturition reflex",
	"Midbrain",
	"Middle cranial fossa",
	"Middle ear anatomy",
	"Middle mediastinum",
	"Migraine",
	"Miliary TB",
	"Mineralocorticoid antagonists",
	"Mineralocorticoid excess",
	"Minimal change disease",
	"Mis-match repair mechanism",
	"Miscarriage",
	"Miscarriage",
	"Missed combined oral contraceptive pills",
	"Missed oral contraceptive pills",
	"Missed oral contraceptive pills",
	"Missed oral contraceptive pills",
	"Mitral Valve Prolapse",
	"Mitral regurgitation",
	"Mitral stenosis",
	"Mixed micelle formation",
	"Molar pregnancy",
	"Molecular Basis of Cancer",
	"Molluscum Contagiosum",
	"Molluscum Contagiosum",
	"Molluscum Contagiosum in Ophthalmology",
	"Monitor BP with tamsulosin - postural hypotension",
	"Monoclonal antibodies",
	"Mononeuritis multiplex",
	"Monosynaptic and polysynaptic reflex arcs",
	"Monteggia and Galeazzi fractures",
	"Monteggia and Galeazzi fractures",
	"Montelukast",
	"Montelukast",
	"Montgomery Ruling",
	"Moral vs Legal Rights",
	"Morphine mechanism of action",
	"Morphine overdose",
	"Mosaicism",
	"Most likely/Common side effect: Pioglitazone (mg gain) (Ddx: bladder cancer/ pulmonary oedema)",
	"Most likely/Common side effect: Pioglitazone (mg gain) (Ddx: bladder cancer/ pulmonary oedema)",
	"Motilin",
	"Motor Neurone Disease",
	"Motor milestones",
	"Motor peripheral neuropathy",
	"Mucosa-associated lymphoid tissue (MALT) lymphoma",
	"Multiple Endocrine Neoplasia",
	"Multiple Sclerosis",
	"Multiple penile ulcers",
	"Mumps",
	"Muscle Biochemistry",
	"Muscle Histology",
	"Muscle Physiology",
	"Muscle Spindle properties",
	"Muscle Spindles",
	"Muscles of Facial Expression",
	"Muscles of eye movement",
	"Muscles of mastication",
	"Muscles of the foot",
	"Muscles of the hand",
	"Muscles of the leg",
	"Muscles of the thigh",
	"Muscles of the thoracic cage",
	"Muscular Dystrophy",
	"Myasthenia Gravis",
	"Myasthenia Gravis",
	"Myelofibrosis",
	"Myeloma",
	"Myelopoiesis",
	"Myocardial infarction and Acute Coronary Syndrome (ACS)",
	"Myocardial infarction and Acute Coronary Syndrome (ACS)",
	"Myocarditis",
	"Myocytes",
	"Myopathy & drugs causing hypokalemia",
	"Myotonic dystrophy",
	"Myxoedema coma",
	"NF1 associated conditions",
	"NG tube positioning",
	"NG tube positioning",
	"NSAID mechanism of action",
	"Naegele's rule",
	"Nasal Blockage",
	"Nasal trauma",
	"Natural killer cells features",
	"Neck: Anterior & Posterior Triangles",
	"Neck: Anterior & Posterior Triangles",
	"Neck: Muscles",
	"Neck: Nerves",
	"Neck: Vasculature",
	"Necrotising enterocolitis",
	"Necrotising fasciitis",
	"Necrotising fasciitis",
	"Necrotising fasciitis",
	"Negative Chronotopes",
	"Negative net fluid balance postop - fluid challenge",
	"Neisseria Gonorrhoea infection",
	"Neisseria Gonorrohoea infection",
	"Neisseria Gonorrohoea infection",
	"Neonatal Herpes Simplex virus infection",
	"Neonatal Respiratory Distress Syndrome",
	"Neonatal mortality and stillbirth",
	"Neonatal resuscitation",
	"Neonatal sepsis",
	"Nephritic syndrome",
	"Nephron structure",
	"Nephrotic syndrome",
	"Nephrotic syndrome",
	"Nerves Of The Pelvis",
	"Nervous System",
	"Neural control of respiration",
	"Neuro-oncology",
	"Neurogenic bladder",
	"Neurological differentials in HIV",
	"Neurological examination in coma",
	"Neuromyelitis optica (Devic's disease)",
	"Neurons of the autonomic nervous system",
	"Neuropathic agents",
	"Neurulation",
	"Neutropenia",
	"Neutropenic sepsis",
	"Neutrophil properties",
	"Neutrophilia",
	"Newborn blood spot screening",
	"Newborn resuscitation",
	"Newborn screening",
	"Nitrofurantoin in LUTI - avoid if eGFR <45. Alternative oral agent is fosfomycin",
	"Nociception fibre classification",
	"Nocturnal enuresis",
	"Non-Hodgkin's lymphoma",
	"Non-accidental Injury",
	"Non-depolarising neuromuscular blocking drugs",
	"Non-invasive ventilation",
	"Normal ECG",
	"Normal Pressure Hydrocephalus",
	"Normal anion gap metabolic acidosis",
	"Nucleotide excision repair",
	"Observational Studies",
	"Obstetric analgesia",
	"Obstetric cholestasis",
	"Obstructive Sleep Apnoea",
	"Obturator nerve",
	"Octreotide",
	"Ocular differentials in HIV",
	"Ocular differentials in HIV",
	"Ocular pain",
	"Ocular side effects of steroids",
	"Ocular tumours",
	"Odds ratio",
	"Oesophageal cancer macroscopic",
	"Oesophageal carcinoma",
	"Oesophageal carcinoma",
	"Oesophagheal atresia",
	"Oesophagitis",
	"Olanzapine - neuroleptic malignant syndrome",
	"Olecranon bursitis",
	"Oligohydramnios",
	"Onchocerciasis",
	"Open Fractures",
	"Open Fractures",
	"Operons",
	"Ophthalmia neonatorum",
	"Opioid conversion- from PO to SC",
	"Opioid receptor activation",
	"Opioid toxicity",
	"Oppositional defiant disorder",
	"Optic disc pallor",
	"Optic disc swelling",
	"Optic neuritis",
	"Optic neuritis",
	"Oral contraceptive pill instructions",
	"Oral contraceptive pill instructions",
	"Oral isotretinoin",
	"Oral isotretinoin",
	"Oral isotretinoin",
	"Oral isotretinoin",
	"Oral lesions",
	"Oral thrush - topical nystatin",
	"Orbital and preseptal cellulitis",
	"Orbital blow out fracture",
	"Organisation of primary lymphoid organs",
	"Organophosphate poisoning",
	"Orphan Concept - from question migration: question with no categories",
	"Orphan Concept - from question migration: question with no categories",
	"Osgood-schlatter's disease",
	"Osteoarthritis",
	"Osteoarthritis",
	"Osteoblasts",
	"Osteochondritis dissecans",
	"Osteoclasts",
	"Osteocytes",
	"Osteogenesis imperfecta",
	"Osteogenesis imperfecta",
	"Osteomalacia",
	"Osteomalacia",
	"Osteomalacia",
	"Osteomyelitis",
	"Osteomyelitis",
	"Osteoporosis",
	"Osteoporosis",
	"Osteoporosis",
	"Osteoporosis",
	"Osteosarcoma",
	"Otitis Externa",
	"Otitis Media",
	"Otosclerosis",
	"Otosclerosis",
	"Ototoxicity & dosing error",
	"Ottawa Ankle Rules",
	"Ovarian Follicle",
	"Ovarian Histology",
	"Ovarian cancer",
	"Ovarian cancer",
	"Ovarian cyst rupture",
	"Ovarian hyperstimulation syndrome",
	"Ovaries",
	"Overactive bladder syndrome",
	"Overactive bladder syndrome",
	"Oxygen Dissociation Curve",
	"Oxygen spectrum of bacteria",
	"P-aminohippurate",
	"P450 inducers",
	"P450 inhibitor and Warfarin",
	"PCOS",
	"PICA syndrome",
	"PPD Skin test",
	"Paediatric Histories",
	"Paediatric Observations",
	"Paediatric basic life support",
	"Paediatric heart failure",
	"Paediatric long bone fractures",
	"Paediatric long bone fractures (Radiology)",
	"Paediatric syndromes with cardiac involvement",
	"Paget's disease",
	"Paget's disease of the bone",
	"Paget's disease of the nipple",
	"Pairing of bases in DNA vs RNA",
	"Pancreatic Cancer",
	"Pancreatic Cancer",
	"Pancreatic activity in cystic fibrosis",
	"Pancreatic amylase",
	"Pancreatic bicarbonate production",
	"Papulosquamous eruptions",
	"Paracetamol Overdose",
	"Paracetamol Overdose",
	"Paracetamol Overdose",
	"Paracetamol Overdose",
	"Paracetamol mechanism of action",
	"Paraphimosis and phimosis",
	"Parasympathetic innervation to the Head and Neck",
	"Parasympathetic nervous system action on the heart",
	"Parkinson's Disease",
	"Parkinson's Disease",
	"Parkinson-plus syndromes",
	"Parkinsonism",
	"Parkinsons disease pathophysiology",
	"Parotid Gland",
	"Paroxetine mechanism of action",
	"Paroxysmal Nocturnal Haemoglobinuria",
	"Partial Agonists",
	"Parvovirus B19",
	"Parvovirus B19",
	"Patellar fracture",
	"Patellar tendinitis",
	"Pathogenesis of TB",
	"Pathological appearance of Sarcoidosis microscopic (granumola)",
	"Pathological appearance of Sarcoidosis microscopic (granumola)",
	"Pathological cytokine responses",
	"Pathological fractures",
	"Pathological hallmarks of neurodegenerative disorders",
	"Pathology of coeliac disease",
	"Pathophysiology",
	"Pathophysiology of Alzheimer's disease",
	"Pathophysiology of Huntington's disease",
	"Pathophysiology of Parkinson's disease",
	"Pathophysiology of erectile dysfunction",
	"Pathophysiology of hemiballismus",
	"Pathophysiology of hydrocephalus",
	"Pathophysiology of lacunar strokes",
	"Pathophysiology of schizophrenia",
	"Pattern recognition receptor features",
	"Patterns of Thyroid Disease",
	"Pectoral muscles",
	"Pediatric dosing error & contraindication",
	"Pedigree chart",
	"Pedigrees",
	"Pellagra",
	"Pelvic Anatomy",
	"Pelvic Viscera—Male",
	"Pelvic inflammatory disease",
	"Pelvic inflammatory disease",
	"Pelvic inflammatory disease",
	"Pemphigus and Pemphigoid",
	"Penetrance",
	"Penicillin activity against bacteria",
	"Penile Erection",
	"Penile skin conditions",
	"Penis",
	"Peptic ulcer disease",
	"Peptic ulcer disease",
	"Pericarditis",
	"Pericarditis",
	"Pericardium",
	"Perineal tears",
	"Perioperative antibiotics",
	"Perioperative management of anaemia",
	"Perioperative management of patients on steroids",
	"Perioperative management of patients on steroids",
	"Perioperative management of patients with COPD",
	"Perioperative management of patients with diabetes",
	"Perioperative management of patients with diabetes",
	"Peripheral actions of testosterone",
	"Peripheral arterial disease",
	"Peripheral chemoreceptors",
	"Peritoneal cavity sub-divisions",
	"Peritonitis",
	"Peritonitis",
	"Pernicious anaemia",
	"Pernicious anaemia",
	"Persistent ductus arteriosus",
	"Perthes disease",
	"Perthes disease",
	"Phaeochromocytoma",
	"Phagocytic cell defects",
	"Phagocytosis",
	"Pharmacokinetics",
	"Pharmacokinetics",
	"Pharmacokinetics",
	"Pharmacokinetics of anti-epileptic drugs",
	"Pharmacological effects of benzodiazepines",
	"Pharmacology of illicit substance misuse",
	"Pharyngeal pouch",
	"Phase 1 reactions",
	"Phase I reactions",
	"Phases of sleep",
	"Phenylephedrine mechanism Of action",
	"Phenylketonuria",
	"Phenytoin toxicity",
	"Pheochromocytoma pathophysiology",
	"Phosphodiesterase (PDE) enzymes and heart failure",
	"Physical barriers of the immune system",
	"Physiological antagonist",
	"Physiological changes associated with anaesthetic drugs",
	"Physiology of erection and ejaculation",
	"Physiology of the inner ear",
	"Physiology of the inner ear",
	"Physiology of the middle ear",
	"Physiology of the middle ear",
	"Pick's disease",
	"Pierre Robin Sequence",
	"Pilonidal abscess",
	"Pinna haematoma",
	"Pituitary disease",
	"Pityriasis rosea",
	"Pityriasis rosea",
	"Placenta praevia",
	"Placental abnormalities (Accreta/Percreta/increta)",
	"Placental abruption",
	"Placental antibody transfer",
	"Plantar Fasciitis",
	"Plantar fasciitis",
	"Pleurae",
	"Pleural effusion",
	"Pleural effusion",
	"Pleural effusion",
	"Plummer-Vinson Syndrome",
	"Pneumocystis Pneumonia",
	"Pneumocystis Pneumonia",
	"Pneumonia",
	"Pneumonia (Infectious Diseases)",
	"Pneumonia (Infectious Diseases)",
	"Pneumonia (Radiology)",
	"Pneumothorax",
	"Pneumothorax",
	"Pneumothorax (Radiology)",
	"Pneumothorax and compliance",
	"Polyarteritis nodosa",
	"Polyarteritis nodosa",
	"Polycystic kidney disease",
	"Polycystic kidney disease",
	"Polycystic kidney disease (paediatrics)",
	"Polycystic ovary syndrome",
	"Polycythaemia",
	"Polyhydramnios",
	"Polymyalgia Rheumatica Association",
	"Polymyalgia rheumatica",
	"Polymyositis and dermatomyositis",
	"Post-coital bleeding",
	"Post-menopausal bleeding",
	"Post-op drug induced constipation & drugs that causes fluid retention",
	"Post-operative nausea and vomiting",
	"Post-operative nausea and vomiting",
	"Post-operative poor urine output",
	"Post-operative poor urine output",
	"Post-operative pyrexia",
	"Post-operative wound infections",
	"Post-partum contraception",
	"Post-streptococcal glomerulonephritis",
	"Posterior Abdominal Wall Muscles",
	"Posterior Forearm muscles",
	"Posterior cranial fossa",
	"Posterior fat pad sign",
	"Posterior inferior cerebellar artery (PICA) syndrome",
	"Posterior mediastinum",
	"Posterior shoulder dislocation",
	"Posterior vitreous detachment",
	"Postmenopausal bleeding",
	"Postnatal contraception",
	"Postnatal thromboprophylaxis",
	"Postnatal thromboprophylaxis",
	"Postpartum depression",
	"Postpartum depression",
	"Postpartum haemorrhage",
	"Postpartum psychosis",
	"Postural Hypotension",
	"Potassium excretion",
	"Potency of general anaesthetic drugs",
	"Potter sequence",
	"Potters syndrome",
	"Prader Willi syndrome",
	"Prader-Willi Syndrome (Genetics)",
	"Pramipexole – compulsive behaviour",
	"Pre-eclampsia",
	"Pre-eclampsia",
	"Pre-implantation genetic diagnosis",
	"Pre-labour rupture of membranes at term",
	"Pre-menstrual Syndrome",
	"Pre-op meds review & paracetamol dosing error",
	"Pre-operative fracture management",
	"Pre-patellar bursitis",
	"Precocious puberty",
	"Prednisolone for minimal change disease - gastric ulceration",
	"Pregnancy Hormones",
	"Pregnancy of unknown origin",
	"Pregnancy of unknown origin",
	"Premature ovarian insufficiency",
	"Premenstrual syndrome",
	"Preseptal and orbital cellulitis",
	"Preterm labour",
	"Priapism",
	"Primary Biliary Cholangitis",
	"Primary HIV Infection",
	"Primary HIV Infection",
	"Primary T cell deficiency",
	"Primary TB",
	"Primary amenorrhoea",
	"Primary biliary cirrhosis",
	"Primary closed angle glaucoma",
	"Primary hyperparathyroidism pathophysiology",
	"Primary immunodeficiency disease",
	"Primary prevention of cardiovascular events",
	"Primary sclerosing cholangitis",
	"Primitive development of the heart",
	"Principle of autonomy",
	"Process of atherosclerosis",
	"Processes in lysosomes",
	"Processes in meiosis",
	"Processes in meiosis",
	"Processes in mitochondria",
	"Processes in mitosis",
	"Processes in mitosis",
	"Processes in smooth and rough endoplasmic reticulum",
	"Processes in the Golgi apparatus",
	"Production of Anti-diuretic hormone",
	"Production of progesterone during pregnancy",
	"Professional Duty of Care",
	"Professionally justifiable reasons for not sharing information",
	"Progestogen-Only Contraception",
	"Prokaryotic vs eukaryotic cells",
	"Properties of Randomised Controlled Trials",
	"Properties of cross-sectional studies",
	"Properties of golgi tendon organs",
	"Properties of golgi tendon organs and muscle spindles",
	"Properties of main chain of amino acids",
	"Properties of meta-analyses",
	"Properties of sensory mechanoreceptors",
	"Properties of sensory mechanoreceptors¶##Linked Recalls",
	"Propranolol mechanism of action",
	"Prostaglandin receptors",
	"Prostanoid receptors",
	"Prostate cancer",
	"Prostate gland",
	"Prostatitis",
	"Protein pump inhibitors and Caesarian sections",
	"Protein pump inhibitors and caesarean sections",
	"Proteinuria",
	"Proteinuria in Children",
	"Proteolytic enzymes of the pancreas",
	"Proteolytic enzymes of the pancreas",
	"Prothrombin Time",
	"Proton pump inhibitors",
	"Pseudo-dementia",
	"Pseudobulbar palsy",
	"Pseudoepiphysis of the 2nd metacarpal",
	"Pseudogout",
	"Pseudohypoparathyroidism",
	"Pseudomembranous colitis",
	"Pseudomonas",
	"Pseudomonas",
	"Psoriasis",
	"Psoriatic arthritis",
	"Psychotherapy",
	"Pterygium",
	"Pterygopalatine fossa",
	"Pudendal nerve",
	"Puerperal mastitis",
	"Pulmonary Embolism",
	"Pulmonary Fibrosis",
	"Pulmonary Hypertension",
	"Pulmonary oedema (Radiology)",
	"Pulmonary stenosis",
	"Pupillary light reflex",
	"Pupillary light reflex physiology",
	"Purines vs pyrimidines in nucleoside triphosphates",
	"Pyelonephritis gross",
	"Pyloric stenosis",
	"Pyoderma gangrenosum",
	"Pyogenic Granuloma",
	"Pyrexia of Unknown Origin",
	"Pyrimidine bases",
	"QT prolongation and citalopram",
	"Quinsy",
	"Radial nerve injuries",
	"Radial nerve injuries",
	"Radiographic features of sickle cell disease",
	"Radioulnar Joints",
	"Radius",
	"Raised anion gap metabolic acidosis",
	"Raised intracranial pressure",
	"Rapid Sequence Induction",
	"Rapidly progressive glomerulonephritis",
	"Rare nutritional disorders",
	"Rash in pregnancy",
	"Rashes in children",
	"Raynaud's phenomenon",
	"Reactive arthritis",
	"Recognising which proteins are globular, fibrous or hybrids",
	"Recognition of acute thoracic dissection",
	"Rectal bleeding",
	"Rectum",
	"Red flag features of vomiting (paediatrics)",
	"Red flag nasal symptoms",
	"Refeeding syndrome",
	"Regulation of internal hydrogen concentration in cells.",
	"Regulation of iron levels",
	"Regulation of sex hormone secretion from the adrenal cortex",
	"Regulation of thyroid hormone secretion",
	"Relationship between oxytocin and vasopressin",
	"Relative risk calculation",
	"Release of pancreatic enzymes",
	"Renal Replacement therapy",
	"Renal Stones",
	"Renal autoregulation",
	"Renal cancer",
	"Renal colic",
	"Renal erythropoietin secretion",
	"Renal erythropoietin secretion",
	"Renal plasma flow",
	"Renal stones",
	"Renal transplant",
	"Renal tubular acidosis",
	"Renal tubular acidosis",
	"Renovascular disease and Renal artery stenosis",
	"Renshaw cells",
	"Requirements of a successful claim for clinical negligence",
	"Reserpine mechanism of action",
	"Resp Physiology",
	"Respiratory Calculations",
	"Respiratory Embryology",
	"Respiratory Failure",
	"Respiratory Infections",
	"Respiratory Pathophysiology",
	"Respiratory alkalosis",
	"Respiratory alkalosis",
	"Respiratory differentials in HIV",
	"Respiratory failure",
	"Restarting normal SC insulin following a VRII",
	"Reticulocytes",
	"Retinal artery occlusion",
	"Retinal detachment",
	"Retinitis pigmentosa",
	"Retinoblastoma",
	"Retinoblastoma (Genetics)",
	"Reye's syndrome",
	"Rhabdomyolysis",
	"Rhabdomyolysis",
	"Rhesus isoimmunisation",
	"Rheumatic fever",
	"Rheumatic fever",
	"Rheumatoid Arthritis",
	"Rheumatoid Hands",
	"Rheumatoid arthritis immunology",
	"Rhinitis hypersensitivity",
	"Rhinosinusitis",
	"Rib structure",
	"Rickets",
	"Rickets",
	"Right bundle branch block",
	"Right heart strain",
	"Right iliac fossa mass",
	"Right iliac fossa pain (General Surgery)",
	"Right iliac fossa pain (General Surgery)",
	"Right iliac fossa pain (Gynaecology)",
	"Right iliac fossa pain (Paediatrics)",
	"Right upper lobe collapse",
	"Right upper quadrant mass",
	"Right upper quadrant pain",
	"Rigler's Sign",
	"Rinne's and Weber's test",
	"Risk",
	"Risk assessment in attempted suicide",
	"Risk factors of post-partum haemorrhage",
	"Risk factors of postpartum haemorrhage",
	"Risks of Caesarean section",
	"Risperidone- galactorrhea, hyperprolactinaemia",
	"Rivaroxaban (antiplatelet) and diclofenac- increased risk of bleeding",
	"Robertsonian Translocations",
	"Role of albumin",
	"Role of aldosterone in acid-base regulation",
	"Role of lung surfactant",
	"Role of stop codons",
	"Role of tRNA",
	"Role of tight junctions",
	"Ropinerole",
	"Roseola Infantum",
	"Rotator Cuff Muscles",
	"Rotator cuff disease",
	"Route Of Adminstration of Gentamicin",
	"Routes Of Adminstration",
	"Routes Of Adminstration of Drugs",
	"Routes of metastasis",
	"Routine HIV testing",
	"Routine monitoring for levothyroxine - by symptoms not TSH/T4",
	"Routine monitoring for levothyroxine - by symptoms not TSH/T4",
	"Rubella",
	"SCC and keratin pearls",
	"SSRI - GI bleeding",
	"SSRI – 6 weeks to work",
	"SSRI – Tapering",
	"ST Elevation MI",
	"Salicylate poisoning",
	"Saliva",
	"Salivary tumours",
	"Salmonella typhi infection",
	"Salt transport in the loop of Henle and the osmotic gradient",
	"Sarcoidosis",
	"Scabies",
	"Scabies and pediculosis pubis",
	"Scaphoid fractures",
	"Scapula",
	"Schistosomiasis",
	"Schizophrenia",
	"Schizophrenia",
	"Sciatic nerve",
	"Scleritis",
	"Seborrhoeic Dermatitis",
	"Seborrhoeic Keratosis",
	"Second order kinetics",
	"Second stage of labour",
	"Secondary Postpartum Haemorrhage",
	"Secondary TB",
	"Secondary amenorrhoea",
	"Secondary amenorrhoea",
	"Secondary causes of diabetes",
	"Secondary hyperparathyroidism pathophysiology",
	"Secretin",
	"Secretion of pancreatic enzymes",
	"Secretion of thyroid hormones",
	"Sedating anti-histamines",
	"Seizure threshold lowering drugs",
	"Seizures and Blackouts",
	"Seizures and Blackouts",
	"Seizures and Blackouts",
	"Seizures in paediatrics",
	"Selection Bias",
	"Selective Serotonin Re-uptake Inhibitors",
	"Seminal vesicles",
	"Sensorineural Hearing Loss",
	"Sensory peripheral neuropathy",
	"Sepsis",
	"Sepsis in children",
	"Septic Arthritis",
	"Septic Arthritis",
	"Septic arthritis (Infectious Diseases)",
	"Septic arthritis and osteomyelitis",
	"Septoplasty",
	"Serotonin syndrome",
	"Serotonin syndrome",
	"Serotonin syndrome",
	"Serous vs glandular epithelia",
	"Sexual Development",
	"Shared features of spondyloarthropathies",
	"Shingles",
	"Shingles",
	"Shingles - oral aciclovir",
	"Shock",
	"Shoulder Dislocation",
	"Shoulder Joint",
	"Shoulder dystocia",
	"Shoulder impingement",
	"Shoulder muscles",
	"Sialadenitis",
	"Sialdenitis",
	"Sick sinus syndrome",
	"Sickle cell disease",
	"Sickle cell disease (Paediatrics)",
	"Side Effects",
	"Side Effects",
	"Side Effects",
	"Side Effects",
	"Side Effects",
	"Side Effects",
	"Side Effects",
	"Side Effects of Ace-inhibitors",
	"Side Effects of Aldosterone antagonists",
	"Side Effects of Aldosterone antagonists",
	"Side Effects of Aminoglycosides",
	"Side Effects of Amitryptiline",
	"Side Effects of Amphetamine",
	"Side Effects of Benzodiazepine",
	"Side Effects of Disulfiram",
	"Side Effects of Drugs used to treat rheumatoid arthritis.",
	"Side Effects of Phenytoin",
	"Side Effects of Radiotherapy",
	"Side Effects of Valproate",
	"Side Effects of Valproate use",
	"Side effects of Flumazenil",
	"Side effects of NSAID use",
	"Side effects of NSAIDs",
	"Side effects of Thiopental",
	"Side effects of adrenaline administration",
	"Side effects of amiodarone",
	"Side effects of anti-diabetic drugs",
	"Side effects of anti-diabetic drugs",
	"Side effects of anti-hypertensives",
	"Side effects of anti-psychotic use",
	"Side effects of antidepressants",
	"Side effects of antidepressants",
	"Side effects of antipsychotics",
	"Side effects of asthma medication",
	"Side effects of bisphosphonates",
	"Side effects of chlorpromazine",
	"Side effects of corticosteroids",
	"Side effects of corticosteroids",
	"Side effects of corticosteroids",
	"Side effects of opioids",
	"Side effects of salbutamol use",
	"Side effects of the combined oral contraceptive pill",
	"Side effects of the progestogen-only contraceptive pill",
	"Sideroblastic anaemia",
	"Silhouette Sign",
	"Simvastatin and transaminases",
	"Single penile ulcers",
	"Sites of airway resistance",
	"Situations in which the law obliges doctors to breach confidentiality",
	"Sjogren's syndrome features",
	"Sjogrens syndrome",
	"Sleeping disorder & dosing error",
	"Slipped Capital Femoral Epiphyses (SCFE)",
	"Slipped Capital Femoral Epiphyses (SCFE)",
	"Slipped upper femoral epiphysis",
	"Small bowel obstruction",
	"Smoking Cessation",
	"Smoking Cessation",
	"Social, emotional and behavioural responses (development)",
	"Sodium nitroprusside mechanism of action",
	"Soft Tissue Infections",
	"Somatic hypermutation and positive selection of B lymphocytes",
	"Somatostatin",
	"Somatotopic arranagement of the motor cortex",
	"Space Occupying Lesions",
	"Space Occupying Lesions",
	"Spaces & Gutters Of The Abdominal Cavity",
	"Spastic hemiparesis",
	"Spastic paraparesis",
	"Specific Side Effects of Chemotherapy",
	"Speculum examination in pregnancy",
	"Spermatogenesis",
	"Spermiogenesis",
	"Spina Bifida",
	"Spina Bifida",
	"Spinal Cord Compression",
	"Spinal Cord Compression",
	"Spinal Meninges",
	"Spinal Stenosis",
	"Spinal claudication",
	"Spirometry",
	"Spironolactone and gynaecomastia",
	"Spironolactone: Uptitration of anti hypertensive medication for patient already on ACE+ BB with K<4.5",
	"Spleen and pneumoccal disease risk",
	"Spleen and pneumoccal disease risk",
	"Splenectomy",
	"Squamous Cell Carcinoma",
	"Stable angina",
	"Stable angina",
	"Stable angina",
	"Stages of Syphilis",
	"Stages of Syphilis",
	"Stages of Syphillis",
	"Stages of pancreatic secretion",
	"Stages of pulmonary development",
	"Stages of urine formation",
	"Standard of care (negligence)",
	"Staphylococcal scalded skin syndrome",
	"Staphylococcal scalded skin syndrome",
	"Staphylococcus",
	"Starling forces and oedema",
	"Statin - myalgia",
	"Statin side Effects",
	"Statins mechanism of action",
	"Statistical Concepts",
	"Statistical Concepts",
	"Statistical Concepts of phase 1 trials",
	"Statistical significance",
	"Status Epilepticus",
	"Status epilepticus (paediatrics)",
	"Step down analgesia post op",
	"Sternoclavicular Joint",
	"Sternum structure",
	"Steroid Sick Day Rule",
	"Steroid conversion",
	"Steroid inhaler",
	"Steroid receptors",
	"Stevens-Johnson syndrome",
	"Stomach cancer",
	"Stomas",
	"Strangulated hernia (paediatrics)",
	"Streptococcal sore throat",
	"Streptococcus",
	"Streptococcus Bovis Investigation",
	"Stress fractures",
	"Stridor",
	"Stridor (paediatrics)",
	"Stroke",
	"Structure and innervation of the GI tract",
	"Structure and physiology of blood vessels",
	"Structure of DNA including bonds",
	"Structure of alpha keratin",
	"Structure of bacteria",
	"Structure of cholesterol",
	"Structure of collagen",
	"Structure of elastin",
	"Structure of fibrinogen",
	"Structure of fibrinogen",
	"Structure of haemoglobin",
	"Structure of haemoglobin",
	"Structure of haemoglobin",
	"Structure of the glomerular filtration barrier",
	"Structure of the respiratory tree",
	"Structure of the small intestine",
	"Styes and chalazions",
	"Subacute combined Degeneration of the Cord",
	"Subarachnoid Haemorrhage",
	"Subclinical Hyperthyroidism",
	"Subclinical Hypothyroidism",
	"Subdiaphragmatic free air",
	"Subdiaphragmatic free air",
	"Subdural Haemorrhage",
	"Subdural Haemorrhage",
	"Subdural haematoma",
	"Substance P",
	"Subtalar joint",
	"Sudden painless visual loss",
	"Sudden painless visual loss",
	"Suitability for PEP",
	"Suitability of COCP",
	"Suitability of COCP",
	"Suitability of COCP",
	"Suitability of the POP",
	"Suitability of the POP",
	"Sulfasalazine",
	"Sulfonylureas",
	"Superficial thrombophlebitis",
	"Superior Vena Cava Obstruction",
	"Superior mediastinum",
	"Supplements and vitamins in pregnancy",
	"Supporting ligaments",
	"Supracondylar fractures of the humerus",
	"Supracondylar fractures of the humerus",
	"Suprapubic mass",
	"Suprapubic pain",
	"Supraventricular Tachycardia",
	"Surfactant",
	"Surgical complications",
	"Surgical third nerve palsy",
	"Survival in cardiac arrest/ROSC of CPR",
	"Survival in cardiac arrest/ROSC of CPR",
	"Sutures",
	"Sutures of the skull",
	"Suxamethonium apnoea",
	"Suxamethonium mechanism of action",
	"Swallowed Battery",
	"Swallowing phases",
	"Sympathetic innervation to the Head and Neck",
	"Sympathetic nerve pathways",
	"Synaptic neurotransmitter function",
	"Syndrome of Inappropriate ADH release (SIADH)",
	"Synthesis and secretion of adrenal cortical hormones",
	"Synthesis and secretion of adrenal cortical hormones",
	"Synthesis of thyroid hormones",
	"Syphilis Serologic Testing Interpretation",
	"Systemic inflammatory response syndrome (SIRS)",
	"Systemic lupus erythematosus (SLE)",
	"Systemic sclerosis",
	"T-cell maturation",
	"T-helper 1 cell activation of macrophages",
	"TB macroscopic",
	"Takayasu's arteritis",
	"Tamoxifen",
	"Tamoxifen",
	"Tamsulosin mechanism of action",
	"Tanner staging of puberty",
	"Target INR levels for different diseases",
	"Target INR levels for different diseases",
	"Target INR levels for different diseases",
	"Target concentration of lithium for acute relapses and frequency of monitoring",
	"Tarsal Tunnel",
	"Temporal lobe epilepsy manifestations",
	"Temporo-mandibular joint dysfunction",
	"Temporo-mandibular joint dysfunction",
	"Teratogenic Side Effects of Phenytoin",
	"Teratogenicity of drugs in pregnancy",
	"Terbinafine for onychomycosis - repeat LFTs at 4 weeks",
	"Termination of pregnancy",
	"Tertiary hyperparathyroidism pathophysiology",
	"Testicular Cancer",
	"Testicular torsion",
	"Testicular torsion",
	"Tetralogy of Fallot",
	"Thalassaemia",
	"The Ankle (Talocrural) Joint",
	"The Cubital Fossa",
	"The Cubital Fossa",
	"The Ear",
	"The Elbow Joint",
	"The Ethmoid bone",
	"The Frank-Starling curve",
	"The Glasgow Coma Scale",
	"The Glasgow Coma Scale",
	"The Glasgow Coma Scale (GCS)",
	"The Hip Joint",
	"The Hip Joint",
	"The Knee Joint",
	"The Knee Joint",
	"The Lumbar Plexus",
	"The Lumbar Plexus",
	"The Mandible",
	"The Mental Health Act",
	"The Mental Health Act and Mental Capacity Act",
	"The Mesenteric Plexus",
	"The Nasal skeleton",
	"The Neuromuscular Junction",
	"The Oral Cavity & Tongue",
	"The Orbit",
	"The Orbit",
	"The Palate",
	"The Pelvic Floor",
	"The Pelvic Floor",
	"The Popliteal Fossa",
	"The Popliteal Fossa",
	"The Shoulder (Glenohumeral Joint)",
	"The Spermatic Cord",
	"The Spermatic Cord",
	"The Sphenoid bone",
	"The Temporal bone",
	"The Tongue",
	"The Uterine Cycle",
	"The Wrist Joint",
	"The Wrist Joint",
	"The cerebrum",
	"The characteristic frequency",
	"The circuit of Papez",
	"The complement system",
	"The cortical reaction",
	"The deep cerebellar nuclei",
	"The effect of oestrogen",
	"The effect of progesterone on the reproductive tract",
	"The effect of the renin-angiotensin system on potassium loss in the distal convoluted tubule",
	"The effect of the renin-angiotensin system on sodium ion uptake in the distal convoluted tubule",
	"The external carotid artery",
	"The eyeball",
	"The eyelids",
	"The flexor withdrawal reflex",
	"The internal carotid artery",
	"The inverse myotatic reflex",
	"The role of CT-Angiogram in acute stroke",
	"The role of Calcitonin in Calcium and Phosphate regulation",
	"The role of Parathyroid Hormone in Calcium and Phosphate regulation",
	"The role of Vitamin D in calcium and phosphate regulation",
	"The role of chest muscles in breathing",
	"The role of the potassium gradient in determining the resting membrane potential",
	"The sodium potassium pump",
	"Thigh: Muscles—Anterior Compartment",
	"Thigh: Muscles—Medial Compartment",
	"Thigh: Muscles—Posterior Compartment",
	"Thigh: Nerves",
	"Thigh: The Femoral Triangle",
	"Thigh: The Femoral Triangle",
	"Thigh: Vasculature",
	"Third nerve palsy",
	"Third stage of labour",
	"Thoracic Outlet Syndrome",
	"Thoracic Outlet Syndrome",
	"Thoracic aorta",
	"Thorax: Anterior Wall",
	"Thorax: Heart—Coronary Arteries & Cardiac Veins",
	"Thorax: Heart—External Anatomy",
	"Thorax: Heart—Internal Anatomy",
	"Thorax: Pericardial Sac",
	"Thorax: The Mediastinum",
	"Thorax: Vasculature",
	"Thrombocytopenia & dosing error",
	"Thrombocytopenia : Dalteparin (Ddx: Ibuprofen, glicazide, furosemide)",
	"Thrombocytopenia : Dalteparin (Ddx: Ibuprofen, glicazide, furosemide)",
	"Thrombophilia",
	"Thromboprophylaxis post-operatively",
	"Thymus gland",
	"Thyroglossal Cyst",
	"Thyroid & Parathyroid Glands",
	"Thyroid Axis",
	"Thyroid cancer",
	"Thyroid eye disease",
	"Thyroid storm",
	"Tibial nerve",
	"Tibial plateau fractures",
	"Tibial shaft fractures",
	"Tibial shaft fractures",
	"Tibiofibular joints",
	"Ticagrelor",
	"Tinea",
	"Tinea",
	"Tinnitus",
	"Titrating insulin with glucose- increase in 10% in previous dosage if premeal BM >7",
	"Tocolysis",
	"Tocolytics",
	"Tonsillitis",
	"Tonsillitis",
	"Torsade de Pointes",
	"Toxic Shock Syndrome",
	"Trabecular bone",
	"Tracheal deviation",
	"Trachoma",
	"Transient Ischaemic Attack",
	"Transient global amnesia",
	"Transient synovitis",
	"Transient synovitis",
	"Transient tachypnoea of the newborn",
	"Transmission of sound waves",
	"Transmural rupture after myocardial infarction",
	"Transport, delivery and metabolism of thyroid hormones",
	"Transposition of great arteries",
	"Treatment",
	"Treatment combinations in tuberculosis",
	"Treatment of Delirium Tremens",
	"Treatment of absence seizures",
	"Treatment of acute pain in trauma",
	"Treatment of bradycardia with adverse features",
	"Treatment of hyperandrogenism in PCOS - co cyprindiol (trade name Dianette)",
	"Treatment of neuropathic pain",
	"Treatments that may be limited following ceiling of care decision.",
	"Trichomoniasis infection",
	"Tricuspid regurgitation",
	"Tricyclic antidepressant overdose",
	"Tricyclic antidepressant overdose",
	"Tricyclic antidepressants mechanism of action",
	"Tricyclic antidepressants mechanism of action",
	"Trigeminal nerve",
	"Trigeminal neuralgia",
	"Trigeminal neuralgia",
	"Trigger finger",
	"Trimethoprim and renal function",
	"Trimethoprim in patients at risk of AKI - potassium most important electrolyte to check",
	"Trisomy disorders",
	"Trochanteric bursitis",
	"Trochanteric bursitis",
	"Troponin",
	"Tuberculosis",
	"Tuberculosis",
	"Tuberculosis",
	"Tuberculosis drugs",
	"Tuberous sclerosis complex",
	"Tubular absorption and secretion",
	"Tubular transport at the loop of Henle",
	"Tubuloglomerular feedback",
	"Tumour Immunology",
	"Tumour Vasculature",
	"Tumour lysis syndrome",
	"Turner syndrome",
	"Turner's syndrome",
	"Turner's syndrome",
	"Twin pregnancies",
	"Twin to twin transfusion syndrome",
	"Twins",
	"Tympanosclerosis",
	"Type 1 diabetes",
	"Type 1 diabetes",
	"Type 1 respiratory failure",
	"Type 2 Diabetes mellitus",
	"Type 2 Diabetes mellitus",
	"Type 2 respiratory failure",
	"Type 3 Type 5 hypersensitivity",
	"Types of Cell Signalling",
	"Types of Memory",
	"Types of Respiratory failure",
	"Types of Respiratory failure",
	"Types of Thyroid Cancer including Pathology",
	"Types of agonists",
	"Types of antibodies and their features",
	"Types of bone marrow",
	"Types of colonic resection",
	"Types of dead space",
	"Types of error",
	"Types of fetal presentation",
	"Types of foetal presentation",
	"Types of genital prolapse",
	"Types of graft rejection",
	"Types of insulins",
	"Types of renal stones",
	"Types of tissue",
	"Types of urinary incontinence",
	"Typhoid",
	"Typhoid fever",
	"Typical antipsychotic",
	"Typical antipsychotics",
	"UC macroscopic",
	"Ulcerative Colitis",
	"Ulnar Canal",
	"Ulnar Tunnel",
	"Ulnar nerve injuries",
	"Ulnar nerve injuries",
	"Ultrasound Imaging",
	"Ultrasound artefacts",
	"Ultrasound guided chest drain insertion",
	"Uncomplicated otitis media - Abx not indicated if <3 days",
	"Undescended testes",
	"Undescended testes",
	"Unfractionated heparin",
	"Upper Arm Muscles",
	"Upper GI bleed",
	"Upper and lower lobe fibrosis",
	"Upper motor neuron lesions",
	"Uptitrating levothyroxine medication based on TFT results",
	"Urea concentration in the medullary interstitium",
	"Ureters",
	"Urethral discharge",
	"Urethral discharge",
	"Urinary tract infection",
	"Urinary tract infection in children",
	"Urinary tract infection in children",
	"Urinary tract infection in children",
	"Urine osmolality",
	"Urogenital Triangle—Female",
	"Urogenital Triangle—Male",
	"Use of Ciprofloxacin",
	"Use of anti-depressants post-MI",
	"Use of cytokines as treatment",
	"Uses of Nitrous oxide",
	"Uterine Tubes",
	"Uveitis",
	"V/Q ratio",
	"VLDL",
	"Vaccination",
	"Vaccinations",
	"Vaccinations",
	"Vaginal Birth After Caesarean section",
	"Valid consent",
	"Validity",
	"Valsalva manoeuvre",
	"Valves of the heart",
	"Vancomycin Resistant Enterococcus",
	"Variceal bleeding",
	"Varicella zoster virus",
	"Varicocele",
	"Varicose veins",
	"Vasa praevia",
	"Vascular Dementia",
	"Vascular Dementia",
	"Vascular dementia",
	"Vasculature Of The Pelvis",
	"Vasculature of the heart",
	"Vasopressin",
	"Veins of the pelvis",
	"Venous Drainage of the arm",
	"Venous Supply of the abdomen",
	"Venous drainage of the brain and meninges",
	"Venous drainage of the brain and meninges",
	"Venous drainage of the lower limb",
	"Venous return and circulatory shock",
	"Venous ulcer disease",
	"Ventricular Septal Defects",
	"Ventricular Septal Defects",
	"Vertigo and Dizziness",
	"Vertigo and Dizziness",
	"Vesicouretric reflux",
	"Vestibular Schwannoma",
	"Viagra",
	"Viral assays in HIV",
	"Virchow's Triad",
	"Virchow's Triad",
	"Viruses",
	"Visual field loss",
	"Visual field loss",
	"Visual field loss",
	"Visual impairment in children",
	"Visual milestones",
	"Visual pathway anatomy",
	"Vital signs in paediatric patients",
	"Vitamin A Deficiency",
	"Vitamin D",
	"Vitamin D activation",
	"Vitamin Deficiency Syndromes",
	"Vitamin K deficiency",
	"Vitamin K deficiency",
	"Vitiligo",
	"Volume, pressure and compliance",
	"Vomiting reflex",
	"Von Willebrand disease",
	"Vulvar cancer",
	"Vulvar cancer",
	"WHO Pain ladder",
	"WHO Pain ladder",
	"WHO Performance Status",
	"Warfarin - high INR",
	"Warfarin mechanism of action",
	"Warfarin-food interaction",
	"Water absorption in the loop of Henle",
	"Water and solute absorption at the proximal convoluted tubule",
	"Water reabsorption",
	"Waterhouse-Friderichsen's syndrome",
	"Weber classification of ankle fractures",
	"Weight-based dosing",
	"Weight-based dosing",
	"Weight-based dosing; calculation of infusion rate",
	"Weight-based dosing; calculation of infusion rate",
	"Weight-based dosing; maximum safe volume of drug that can be administered",
	"Wellen's syndrome",
	"Wernicke's encephalopathy",
	"Wernicke's encephalopathy and Korsakoff's Syndrome Pathophysiology",
	"Wernicke's encephalopathy and Korsakoff's syndrome",
	"Wernicke's encephalopathy and Korsakoff's syndrome",
	"Wernicke's encephalopathy and Korsakoff's syndrome",
	"Wernicke's encephalopathy and Korsakoff's syndrome",
	"Wet and dry gangrene",
	"What germ layers go on to form:",
	"When DNACPR decisions should be communicated to patients",
	"When trying to get pregnant - start high dose folic acid",
	"Whipple's disease",
	"White Blood Cell Characteristics",
	"Whooping cough",
	"Whooping cough (pertussis)",
	"Wilm's tumour (nephroblastoma)",
	"Wilms tumours",
	"Wilson's disease",
	"Wilson's disease",
	"Wilson's disease",
	"Withholding drugs post op AKI",
	"Wobble hypothesis",
	"Wolff-Parkinson-White syndrome",
	"Wolff-Parkinson-White syndrome",
	"Zenker's diverticulum",
	"Zenkers Diverticulum",
	"Zero order kinetics",
	"Zollinger-Ellison Syndrome",
	"a-methyltyrosine mechanism of action",
	"b1-adrenoceptors",
	"cANCA vs pANCA vasculitides",
	"non-Hodgkin's lymphoma",
}

func createRegex(arr []string) *regexp.Regexp {
	conceptNameArr := lo.Uniq[string](arr)
	// build expression of all concept names
	expression := "(?i)\\b("
	for i, name := range conceptNameArr {
		if i != 0 {
			name = "|" + name
		}
		expression = expression + name
	}
	expression = expression + ")\\b"
	r := regexp.MustCompile(expression)
	return r
}

type matchObj struct {
	lineIdx    int
	match      string
	start, end int
}

func populate(r *regexp.Regexp, str string) string {
	lines := strings.Split(str, "\n")
	allMatches := make([]matchObj, 0)

	var wg sync.WaitGroup

	for i, line := range lines {
		wg.Add(1)
		go findLineMatches(&wg, r, i, line, &allMatches)
	}
	wg.Wait()
	// fmt.Printf("%+v\n", allMatches)
	if len(allMatches) == 0 {
		return str
	}
	matchIdx := 0
	lineIdx := allMatches[matchIdx].lineIdx
	newLines := make([]string, len(lines))
	for i, line := range lines {
		if i != lineIdx {
			newLines[i] = lines[i]
			continue
		}
		currMatch := allMatches[matchIdx]
		matchIdx = matchIdx + 1

		if len(allMatches) > matchIdx {
			lineIdx = allMatches[matchIdx].lineIdx
		} else {
			lineIdx = -1
		}
		newLines[i] = fmt.Sprintf(`%s<u data-topicId="{matchingConcept.topicId}" data-conceptId="{matchingConcept.conceptId}" data-chapterId="{matchingConcept.chapterId}">%s</u>%s`, line[0:currMatch.start], currMatch.match, line[currMatch.end:])
	}

	return strings.Join(newLines, "\n")
}

func findLineMatches(wg *sync.WaitGroup, r *regexp.Regexp, lineIdx int, line string, matchesList *[]matchObj) {
	defer wg.Done()
	if line == "" || line[0] == '#' || strings.Contains(line, "http") {
		return
	}
	indexMatches := r.FindAllStringIndex(line, -1)
	for _, index := range indexMatches {
		start := index[0]
		end := index[1]
		tmp := matchObj{lineIdx, line[start:end], start, end}
		*matchesList = append(*matchesList, tmp)
	}
}

func main() {
	r := createRegex(conceptNameList)
	res := populate(r, md)
	fmt.Println(res)
}
